### ISSUE TITLE
[sqlite3_flutter_libs] no such column on windows

### ISSUE THREAD

**Issue by clragon** [simolus3/sqlite3.dart#101]
I was attempting to use `sqlite3_flutter_libs`  to make my windows release build automatically come with an appropriate `sqlite3.dll`.
However, it seems that when doing so, a "no such column" exception occurs. I do not have much knowledge about the inner workings of SQL or SQL queries in general, so I cannot say with certainty why this exception happens.

I have attached a log of the exception below.

I have also made the observation, that when replacing the bundled `sqlite3.dll` with the [one](https://github.com/tekartik/sqflite/raw/master/sqflite_common_ffi/lib/src/windows/sqlite3.dll) provided by the [`sqflite_common`](https://pub.dev/packages/sqflite_common_ffi) package, which is also automatically bundled on windows in debug mode only, it works fine. I have checked the file hashes and they are not identical, but beyond that I dont know the difference.

I assume that the package that is making those SQL queries is not the issue, since it is working fine when using the `sqflite_common` dll and on any mobile device which does not need a bundled sql dependency. However, I have included its version in the package declarations anyways.

#### packages
```yaml
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  sqflite: ^2.0.2+1
  sqflite_common_ffi: ^2.1.0 # used to change the databaseFactory for windows/linux
  sqlite3_flutter_libs: ^0.5.7 # used to provide sqlite3.dll
  dio_http_cache: ^0.3.0 # listed because its in the stacktrace
```

#### flutter & OS
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.22000.675])
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.9)
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

#### logs
```
SqfliteFfiException(sqlite_error: 1, , SqliteException(1): no such column: 90F1945F11663E6325B003447958F6C2, SQL logic error (code 1)
  Causing statement: SELECT * FROM cache_dio WHERE key="90F1945F11663E6325B003447958F6C2" and subKey="7174C7C5BF20B3A70D5CB595FBF80090"}) DatabaseException(SqliteException(1): no such column: 90F1945F11663E6325B003447958F6C2, SQL logic error (code 1)
  Causing statement: SELECT * FROM cache_dio WHERE key="90F1945F11663E6325B003447958F6C2" and subKey="7174C7C5BF20B3A70D5CB595FBF80090") sql 'SELECT * FROM cache_dio WHERE key="90F1945F11663E6325B003447958F6C2" and subKey="7174C7C5BF20B3A70D5CB595FBF80090"' {details: {database: {path: C:\Users\dragon\AndroidStudioProjects\e1547\build\windows\runner\Release\.dart_tool\sqflite_common_ffi\databases\DioCache.db, id: 1, readOnly: false, singleInstance: true}}}
SqfliteFfiException(sqlite_error: 1, , SqliteException(1): no such column: 90F1945F11663E6325B003447958F6C2, SQL logic error (code 1)
  Causing statement: SELECT * FROM cache_dio WHERE key="90F1945F11663E6325B003447958F6C2" and subKey="BFFBF7565118B1E24F1C2C73F0AC0E69"}) DatabaseException(SqliteException(1): no such column: 90F1945F11663E6325B003447958F6C2, SQL logic error (code 1)
  Causing statement: SELECT * FROM cache_dio WHERE key="90F1945F11663E6325B003447958F6C2" and subKey="BFFBF7565118B1E24F1C2C73F0AC0E69") sql 'SELECT * FROM cache_dio WHERE key="90F1945F11663E6325B003447958F6C2" and subKey="BFFBF7565118B1E24F1C2C73F0AC0E69"' {details: {database: {path: C:\Users\dragon\AndroidStudioProjects\e1547\build\windows\runner\Release\.dart_tool\sqflite_common_ffi\databases\DioCache.db, id: 1, readOnly: false, singleInstance: true}}}
```

**Comment by simolus3** [comment]
The problem is the `"` around the string literal. The sqlite3 version that `sqlite3_flutter_libs`  includes is compiled as part of your Flutter build with [a recommended set of compile-time options](https://www.sqlite.org/compile.html#recommended_compile_time_options). Sqlite3 developers recommend disabling support for double-quoted strings, and so it is not supported when using sqlite3 with `sqlite3_flutter_libs`.

If you wrote that query manually, change the `"90F1945F11663E6325B003447958F6C2"` to `'90F1945F11663E6325B003447958F6C2'` (with single quotes). If this comes from a cache package for dio, you should open an issue on that package and ask them to generate SQL with single-quoted strings. Strings with double quotes are not supported by the ANSI SQL standard and their use is strongly discouraged by sqlite3 developers. Unless there is a very good reason to change this, I'm not interested in deviating from recommended compile options for sqlite3.

**Comment by clragon** [comment]
thank you for taking a look. 
I will attempt to get this fixed in the dio cache package then.

For anyone stumbling upon this issue, its unlikely this is fixed 
considering the maintenance cycle of the dio http cache package.

I would recommend switching to dio cache interceptor then.
