### ISSUE TITLE
how to download file.sqlite with sqlite3.wasm?

### ISSUE THREAD

**Issue by imoldfella** [simolus3/sqlite3.dart#102]
I did this which makes sense to me
```dart
getDb(IndexedDbFileSystem fs, String s) async {
  final response = await http.get(Uri.parse(s));
  print("received ${response.contentLength}");
  fs.createFile(s);
  fs.write(s, response.bodyBytes, 0);
  fs.flush();

  final buffer = Uint8List(response.contentLength!);
  fs.read('simplefolks.sqlite', buffer, 0);
  print("equal ${listEquals(buffer, response.bodyBytes)}");
}

  const String fn = 'simplefolks.sqlite';
  await getDb(fs, fn);

  final db = dbx.open(fn); // , mode: OpenMode.readWrite

  final ResultSet resultSet = db.select('SELECT * FROM people');
  for (final element in resultSet) {
    out.write(element);
  }
```

It's the same 9216 bytes as on the server, there select * from people works, but after downloading and opening like
```
Error: SqliteException(1): no such table: people, SQL logic error (code 1)
  Causing statement: SELECT * FROM people
```
If I tried to use read only, then it throws parameter misuse.

I'm going to keep looking into this, but wondered if its known that this can't work or if I'm doing something obviously stupid. Using flutter 3/ chrome/ mac.

Thanks!

**Comment by simolus3** [comment]
At the moment, the file system API is a bit tricky to use manually - there are small differences in how sqlite3 handles files that can have an impact here. In particular, sqlite will normalize a path (which also makes it absolute) and the current file system is designed to expect normalized paths (so `simplefolks.sqlite` and `/simplefolks.sqlite` are different files).

Does it work if you use `/simplefolks.sqlite` as a path for the direct file system manipulation?

**Comment by imoldfella** [comment]
Perfect! I changed everything to /simplefolks.sqlite and it works like a charm! Thanks for getting back so fast and thanks for such a cool project!
