### ISSUE TITLE
Dispose does not release the file on an Amazon EFS drive

### ISSUE THREAD

**Issue by cabbi** [simolus3/sqlite3.dart#106]
Once i call dispose, trying to delete the database file fails since it is still locked.

**Comment by simolus3** [comment]
Can you show a small snippet that reproduces this behavior? For me, this works:

```dart
import 'dart:io';

import 'package:sqlite3/sqlite3.dart';

void main() {
  final db = sqlite3.open('/tmp/foo.db');
  db.execute('CREATE TABLE foo (bar);');
  db.execute('BEGIN;');
  db.dispose();

  File('/tmp/foo.db').deleteSync();
}
```

**Comment by cabbi** [comment]
I've tested my environment with a simple python test and it runs by deleting the file
```
import os
import sqlite3 as s

def lambda_handler(event, context):
    con = s.connect("/mnt/jobucket/data.db")
    cur = con.cursor()
    cur.execute('CREATE TABLE IF NOT EXISTS artist(ArtistId INTEGER PRIMARY KEY AUTOINCREMENT,Name NVARCHAR);')
    cur.execute('INSERT INTO artist (name) VALUES ("Buddy Rich"), ("Candido"), ("Charlie Byrd");')
    records = []
    for a in cur.execute("SELECT * FROM artist"):
        records.append(a)
    con.commit()
    con.close()
    os.remove("/mnt/jobucket/data.db")
    return {
        'statusCode': 200,
        'body': records
    }
```
python "close" might do something different/more than your "dispose"

**Comment by simolus3** [comment]
Could you post the Dart code that you're using at the moment to close the database and delete the file? For a good comparison, it would be helpful to have a Dart-equivalent of that Python snippet, maybe that helps to see where things might be going differently.

**Comment by cabbi** [comment]
I've found the why I'm facing this issue: is you call multiple times 'open', then the 'dispose' is not releasing the file. Not sure if you can handle somehow this scenario.

Here is your modified example failing:

```
import 'dart:io';

import 'package:sqlite3/sqlite3.dart';

void main() {
  var db = sqlite3.open('/tmp/foo.db');
  db = sqlite3.open('/tmp/foo.db');
  db.execute('CREATE TABLE foo (bar);');
  db.execute('BEGIN;');
  db.dispose();

  File('/tmp/foo.db').deleteSync();
}
```

**Comment by cabbi** [comment]
It is obvious that opening multiple connections requires closing each of them.

Going to close this issue
