### ISSUE TITLE
'open' ignores the 'mutex' parameter

### ISSUE THREAD

**Issue by cabbi** [simolus3/sqlite3.dart#107]
from your implementation DatabaseImpl.open call is missing the 'mutex' parameter:

```dart
  @override
  Database open(
    String filename, {
    String? vfs,
    OpenMode mode = OpenMode.readWriteCreate,
    bool uri = false,
    bool? mutex,
  }) {
    return DatabaseImpl.open(
      _library,
      filename,
      vfs: vfs,
      mode: mode,
      uri: uri,
      // --> mutex is missing
    );
  }

```

**Comment by simolus3** [comment]
Thanks! I've fixed this in d55d9b5ae43a2e95e6c0507325b49f9ea4e0bd1d. It's probably not too relevant in practice, since it only affects the threading mode (and not file locking). In virtually all cases, you're using a sqlite3 connection on one Dart isolate only so the default is fine.
