### ISSUE TITLE
Implement Insert Bind Parameters functionality

### ISSUE THREAD

**Issue by Rockvole** [simolus3/sqlite3.dart#11]
Please provide a function for an insert query which binds a list of values to ?'s

An example of this in the sqflite library is rawInsert()
https://github.com/tekartik/sqflite/blob/master/sqflite_common/lib/sqlite_api.dart

An example of this in the mysql1 library is query()
https://github.com/adamlofts/mysql1_dart/blob/master/lib/src/single_connection.dart

Thank-you.

**Comment by simolus3** [comment]
What exactly are you trying to do here? You can run an insert with

```dart
final stmt = database.prepare('INSERT INTO ...');
stmt.execute([your, parameters]);
stmt.dispose();
```

This library is supposed to be a relatively low-level wrapper around sqlite3's C-bindings, so I don't think we need a method to simplify this pattern. You can also use this library with sqflite's apis through the [sqflite_common_ffi](https://pub.dev/packages/sqflite_common_ffi) package.

**Comment by Rockvole** [comment]
Sorry, I didn't read your example carefully enough and couldn't find anything which looked appropriate looking through the available functions in Intellij.
