### ISSUE TITLE
An error 14 (

### ISSUE THREAD

**Issue by ralfeus** [simolus3/sqlite3.dart#110]
I'm trying to use `sqlite3` at the Android device. So I create an empty Flutter project and add only following lines:

pubspec.yaml
```
dependencies:
  sqlite3_flutter_libs: '>=0.5.8'
  sqlite3: '>=1.7.2'
```
main.dart
```
void main() {
  sqlite3.open("test.sqlite3"); // This one is added
  runApp(const MyApp());
}
```

When I run it at the Linux device, no problem occurs.
When I run it at the Android emulator or real device I get an error:

> E/flutter ( 8446): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: SqliteException(14): bad parameter or other API misuse, bad parameter or other API misuse (code 21)
> E/flutter ( 8446): #0      new DatabaseImpl.open
> package:sqlite3/…/impl/database.dart:47
> E/flutter ( 8446): #1      Sqlite3.open
> package:sqlite3/…/api/sqlite3.dart:44
> E/flutter ( 8446): #2      main
> package:test_flutter/main.dart:5

Are any permissions have to be set specific for Android?

**Comment by ralfeus** [comment]
What I've learned is that DB file must be created in the specific path. `sqflite` has `getDatabasesPath()` function that calls native one and returns the path where the database can be created. Is there anything like that in `sqlite3`?

**Comment by simolus3** [comment]
> Are any permissions have to be set specific for Android?

The error occurs because your app has no permission to write to `test.sqlite` (to be fair, I don't know what the cwd is for Android apps). On Android, you should write into a directory recognized for storing application data.

> `sqflite` has `getDatabasesPath()` function that calls native one and returns the path where the database can be created. Is there anything like that in `sqlite3`?

No, because `getDatabasesPath()` is an OS-specific feature that is not part of the `sqlite3` library (`sqflite` uses an Android or iOS-specific API to get this oath). Instead, you can use a package like `path_provider` to get a suitable folder:

```dart
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as path;

// then use:
final dbFolder = await getApplicationDocumentsDirectory();
sqlite3.open(path.join(dbFolder.path, 'test.sqlite3'));
```

**Comment by nay-kang** [comment]
@simolus3 may I suggest put this code to the example.
it's hard for beginners to find how to proper set the database path.
