### ISSUE TITLE
regexp support ?

### ISSUE THREAD

**Issue by odrevet** [simolus3/sqlite3.dart#116]
Is it possible to enable regexp support under linux, when manually providing sqlite3 libraries ? 
This [StackOverflow post ](https://stackoverflow.com/a/8338515/2323803) explains to install sqlite3-pcre and then load it with `.load /usr/lib/sqlite3/pcre.so`
Is it something doable with your library ?

**Comment by simolus3** [comment]
At the moment, we don't support dynamically loaded extensions, but I'll take a look at adding support for this to this package. Once it's done, I can also provide an example on how to load the sqlite pcre extension through that mechanism.

**Comment by simolus3** [comment]
That said, you can also just register a function to use Dart's regex API instead:

```dart
  yourDatabase.createFunction(
    functionName: 'regexp',
    function: (args) {
      final pattern = RegExp(args[0].toString());
      return pattern.hasMatch(args[1].toString());
    },
    argumentCount: const AllowedArgumentCount(2),
    deterministic: true,
    directOnly: false,
  );
```

Then you can also use the `REGEXP` operator afterwards.

**Comment by odrevet** [comment]
This works ! thanks !
