### ISSUE TITLE
Freeze when query is pending

### ISSUE THREAD

**Issue by odrevet** [simolus3/sqlite3.dart#119]
I am using sqlte3 with flutter, and when a query is running with a call using the "select" function, the interface freeze. 
I suppose it's because select is not an async function. Is there a use case to call the select function in the background (while showing a progressIndicator) I tried to wrap calls into an async function but the UI freeze anyway.

**Comment by simolus3** [comment]
You are right - the C APIs from `sqlite3` which this package is calling are synchronous and blocking. There's no simple solution to this - calling a synchronous function in an `async` function doesn't make it any less blocking.

The best solution is to offload your sqlite3 connection to a background database. You could write this yourself, but it's tedious. There are two packages (that I'm aware of) which can do this for you:

- [sqflite_common_ffi](https://pub.dev/packages/sqflite_common_ffi): This uses `sqlite3` internally, but manages an isolate for you and presents the database as an asynchronous API.
- [drift](https://drift.simonbinder.eu/): This package (which I've written) provides a bunch of additional convenience features around sqlite3, including a complex Dart query builder. I can also manage an isolate for you to transparently run queries in the background.

If you need something simple to just make sqlite3 asynchronous, I recommend the first package. If some of the features drift provides sounds interesting to you, you can use that one as well.
