### ISSUE TITLE
sqlcipher on other OS ?

### ISSUE THREAD

**Issue by MobiliteDev** [simolus3/sqlite3.dart#12]
Hi,

First of all, thank for you library sqlite3.

You allow to use sqlcipher  for Android and iOS, but, do you plan to provide this functionnality for other OS ? Like Windows, MAC and Linux ?

**Comment by simolus3** [comment]
Neither `sqlite_flutter_libs` nor `sqlcipher_flutter_libs` works outside of Android or iOS. For other platforms, you'll need something custom to use the library, but it's not a lot of work.

You could download SQLCipher binaries or build libraries from [here](https://github.com/sqlcipher/sqlcipher) and then use a [custom open behavior](https://pub.dev/packages/sqlite3#manually-providing-sqlite3-libraries) to use that library.

**Comment by MobiliteDev** [comment]
Thank you for your answer, I will see to generate my own libraries.

**Comment by simolus3** [comment]
Great! Let me know if you run into problems with that.

**Comment by MobiliteDev** [comment]
@simolus3 For information, I've just uploaded a package with SQLCipher DLL for Windows on pub.dev.

https://pub.dev/packages/sqlcipher_library_windows
