### ISSUE TITLE
FTS4 engine support?

### ISSUE THREAD

**Issue by hurelhuyag** [simolus3/sqlite3.dart#124]
Today I found out `sqlite3_flutter_libs: 0.5.10`  is not supported fts4 engine. Any plan for the full-text engine?
```
    CREATE VIRTUAL TABLE textContent USING fts4(
        text, tokenize=icu mn_MN
    )
```

Ref: https://www.sqlite.org/fts3.html

**Comment by simolus3** [comment]
We support fts5 in `sqlite3_flutter_libs` on all platforms. I don't see a good reason to support previous fts iterations as well. The compiled binaries should be reasonably small, so I don't want to enable too many extensions.
