### ISSUE TITLE
Issues loading or instantiating WebAssembly module

### ISSUE THREAD

**Issue by stx** [simolus3/sqlite3.dart#128]
We're randomly seeing this error show up in Sentry error reports on Flutter web when using Drift. Seen across the last few sql-wasm versions, on Chrome and Edge:

Error: LinkError: WebAssembly.instantiate(): Import #0 module="a" function="a" error: function import requires a callable

Maybe due to the deferred loading script tag? Or an ad or JavaScript blocker?

**Comment by simolus3** [comment]
Thanks for the report. Do you have the Chrome/Edge versions this is happening on? It could be some client-side blocking, but since the wasm has started loading and fails at verification, maybe it's an old browser?

**Comment by stx** [comment]
Latest of both. Edge 107, Chrome 106.

**Comment by simolus3** [comment]
That's probably not the original root cause, but I wonder if this could be related to the way the module is loaded (perhaps because we get an invalid response when loading `sqlite3.wasm` and pass that to `WebAssembly.instantiate`)...

In the latest version of this package, you can use `WasmSqlite3.loadFromUrl` to load the module from an URI with a direct `fetch()`  call instead of using the `http` package. This is more efficient in general, and I wonder if it could fix this problem as well.

**Comment by stx** [comment]
@simolus3 Happy to give this a try but I'm not sure how we're supposed to migrate to this?

We're using the prior implementation on https://drift.simonbinder.eu/web/.

I understand that we should remove `sql-wasm.js` and use `WasmSqlite3.loadFromUrl()` but I don't see how to make that work when we need a `Database` returned (with our migrationStrategy, methods, etc.), like in the below:

```
  return Database(
    WebDatabase.withStorage(
      await DriftWebStorage.indexedDbIfSupported('db'),
      logStatements: logStatements,
    ),
  );
```

The docs don't appear to address this. How do you get a `Database` from a `WasmDatabase`?

**Comment by stx** [comment]
@simolus3

Results below. Works but new problems.

https://github.com/simolus3/drift/issues/2384
https://github.com/simolus3/drift/issues/2383

**Comment by stx** [comment]
Added some detailed network logging to help identify the issues.

These issues:

* Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
* CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
* CompileError: wasm validation error: at offset 4: failed to match magic number

Are due to:

1. Partial downloads due to user and network interrupts.
2. When the file no longer exists because old Flutter code is running after changing implementation methods. Some definite weirdness going on here with Flutter's PWA strategy.

This issue:

* Error: LinkError: WebAssembly.instantiate(): Import #0 module="a" function="a" error: function import requires a callable

Is due to `sql-wasm.js` not getting loaded or requested by the browser for whatever reason. Seems like extensions are the most common culprit.

Not sure that Drift is going to be able to do anything about these things.

**Comment by willsmanley** [comment]
For anyone googling this issue, I also get this issue sometimes with drift (https://github.com/simolus3/drift), also from simolus3, which depends on sqlite3:

Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

Haven't solved it yet but didn't notice where this error was coming from for a while until finding this thead.

FWIW, no browser extensions causing this issue, i think i just dont have drift set up properly for web yet. Will update here.
