### ISSUE TITLE
Flags for Database.open()

### ISSUE THREAD

**Issue by yupi** [simolus3/sqlite3.dart#13]
Please, allow to use other flags in Database.open() method like SQLITE_OPEN_FULLMUTEX.

**Comment by simolus3** [comment]
Do you only need the mutex flags? I'm reluctant to expose the flag int as a parameter since the library sets most flags internally (for the open mode and uri vs file). AFAIK parameters controlling visibility of the cache can also be set via a uri parameter, so mutex and and `SQLITE_OPEN_NOFOLLOW` are the only ones remaining.

**Comment by yupi** [comment]
For my purposes, yes, i'd like to be sure my sqlite has serialized access because it is used from different isolates.

**Comment by simolus3** [comment]
I added a `mutex` option for this, I'll release the next version soon. 

> i'd like to be sure my sqlite has serialized access because it is used from different isolates

Unless your sharing a database pointer across isolates (don't do this!), the default multi-threading mode is fine. You won't need a full mutex if each isolate opens a database by itself, even if they all point to the same file.

**Comment by yupi** [comment]
> I added a `mutex` option for this, I'll release the next version soon.
Thanks, awesome.

> 
> > i'd like to be sure my sqlite has serialized access because it is used from different isolates
> 
> Unless your sharing a database pointer across isolates (don't do this!), the default multi-threading mode is fine. You won't need a full mutex if each isolate opens a database by itself, even if they all point to the same file.

That would solve my problem, but i am not sure it is easy to do. I can run only global or static functions with simple args in the isolate, so no state. Does an isolate have access to a static object property created in other isolates?

**Comment by simolus3** [comment]
> Does an isolate have access to a static object property created in another isolate?

It does not, isolates have separate memory and only communicate by sending messages.

> I can run only global or static functions with simple args in the isolate, so no state

Exactly, that's why you won't accidentally use a `Database` object across multiple isolates. So you might not need the full mutex option at all. Regardless, it's available in version 0.18 of this package.
