### ISSUE TITLE
Could not find sqlite3-native-library-3.39.4.jar

### ISSUE THREAD

**Issue by TetrixGauss** [simolus3/sqlite3.dart#131]
Hello there! Without changing actually anything on the part of the sqlite3 or drift package, I just got this message on the pipeline of my application build! 

```
Execution failed for task ':sqlite3_flutter_libs:compileReleaseJavaWithJavac'.
> Could not resolve all files for configuration ':sqlite3_flutter_libs:releaseCompileClasspath'.
   > Failed to transform sqlite3-native-library-3.39.4.jar (eu.simonbinder:sqlite3-native-library:3.39.4) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find sqlite3-native-library-3.39.4.jar (eu.simonbinder:sqlite3-native-library:3.39.4).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/eu/simonbinder/sqlite3-native-library/3.39.4/sqlite3-native-library-3.39.4.jar
```

I have the latest versions Flutter 3.3.7 and on sqlite3 0.5.11 . 

Any suggestions ?

**Comment by simolus3** [comment]
Thanks for the report. It looks like something went wrong publishing to maven central. I have retraced the broken `sqlite3_flutter_libs` version and I'll push a fix asap.

**Comment by simolus3** [comment]
Should work with `sqlite3_flutter_libs` version `0.5.11+1`, which I've just released. If you're running into more issues, please let me know.

Apologies again for the inconvenience!
