### ISSUE TITLE
load extension in android & iOS

### ISSUE THREAD

**Issue by SNNafi** [simolus3/sqlite3.dart#132]
`sqlite3.sqlite3.ensureExtensionLoaded();`

Does it work with Android? I am asking as there is no test [here](https://github.com/simolus3/sqlite3.dart/blob/main/sqlite3/test/ffi/sqlite3_test.dart), for the android platform.

**Comment by simolus3** [comment]
It should work with Android as well. It really only calls `sqlite3_auto_extension` with a function pointer. At the moment, there is no test for this on Android though (contributions are welcome!).

**Comment by SNNafi** [comment]
Hey, hope you are well. I am facing strange behavior while loading extensions in android & ios. Working fine with macOS & windows. 

It doesn't load the SQLite extension when the app launches but after a hot restart it is working fine!

I am using this with `sqflite_common_ffi`. Here is the [demo](https://github.com/GreentechApps/tokenizer_flutter_demo/) project link.

I don't know if the issue is in the sqlite3 or not. Just give it to your knowledge.

Again thanks for this awesome plugin

**Comment by SNNafi** [comment]
Fixed. We need to first load the extension, then the database.
