### ISSUE TITLE
I could'nt have found find sqlite3.wasm or sqlite.wasm

### ISSUE THREAD

**Issue by brilliapps** [simolus3/sqlite3.dart#133]
As in the title. The docs say it is easy to download sqlite.wasm from sqlite3 github repositories, but i cannot find it anywhere. Am i blind? Finally i noticed that tekartik user (name like that) gives link to use-ready sqlite.wasm file.
https://pub.dev/packages/sqflite_common_ffi

However, finally, i got an instance of 'WasmSqlite3' object

did this from the example:
`      db.execute('''
        CREATE TABLE artists (
          id INTEGER NOT NULL PRIMARY KEY,
          name TEXT NOT NULL
        );
        ''');
`
and got this error:
NoSuchMethodError: 'execute'

This method should be available as i see in the docs so i thought tekartik gave that link to some older version of the sqlite.wasm file

C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart
266:49      throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart
735:3   defaultNoSuchMethod
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 61:17
noSuchMethod
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart
730:31  noSuchMethod
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart
280:9   _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart
398:10  callMethod
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart
402:5   dsend

Just wanted to say - i am not into compilation or something. I am just from js/html world and need it working. Would be happy if someone told me where to get the .wam file :) .

**Comment by simolus3** [comment]
Could you run `flutter clean` once? `db.execute` should definitely exist. That error doesn't come from wasm, it's probably something broken with the Dart compilation.

> Would be happy if someone told me where to get the .wam file :) .

You can grab it from the assets of the latest release [here](https://github.com/simolus3/sqlite3.dart/releases/tag/sqlite3-1.9.1).

**Comment by brilliapps** [comment]
First, thank you for your answer and overall work. This didn't work, I will probably need to 'flutter upgrade' to a new version and maybe it will repair the current one 3.3.0 i have. When i'am done and successful i going to inform you what was the cause.

**Comment by brilliapps** [comment]
I replaced, not upgraded, the old flutter installation with the newest (windows 10 64-bit). It doesn't work either. If i ever find out what going on i will inform you. Please don't take more time for it.

**Comment by brilliapps** [comment]
I've forgotten about something additional. In the example from https://pub.dev/packages/sqlite3 
i cannot use IndexedDbFileSystem.load('/');, but i could find in the doc open method and it worked ok, end finally it indeed got me the WasmSqlite3 db object:
    final fs = await IndexedDbFileSystem.open(
        dbName:
            'test' /*'condition_data_management_driver_sql_dot_web_dot_dart'*/);

pubspec yaml
  sqlite3: ^1.9.1

And it doesn't see the exec method - full code below, but the object is WasmSqlite3 db object.
Visual Express also doesn't see this method. it isn't defined - something like i got an older version of the extension


this is how it looks in my code

```
import 'package:http/http.dart' as http;
import 'package:sqlite3/common.dart';
static dynamic getDbEngine() async {
//https://pub.dev/documentation/sqlite3/latest/
//Future<WasmSqlite3> loadSqlite() async {
    final response = await http.get(Uri.parse('sqlite3.wasm'));
    final fs = await IndexedDbFileSystem.open(
        dbName:
            'test' /*'condition_data_management_driver_sql_dot_web_dot_dart'*/);

    WasmSqlite3 db = await WasmSqlite3.load(
        response.bodyBytes, SqliteEnvironment(fileSystem: fs));

    print('''
        CREATE TABLE tests (
          id INTEGER NOT NULL PRIMARY KEY,
          name TEXT NOT NULL
        );
        ''');
    // not seeing execute
    db.execute('''
        CREATE TABLE tests (
          id INTEGER NOT NULL PRIMARY KEY,
          name TEXT NOT NULL
        );
        ''');

    return db;
}

```

**Comment by brilliapps** [comment]
I have a question: are this closed issue read? Please let me know
I created a new project and nothing, JUST started digging into the code of the sqlite3 library.
I see two things that seems to me having to do with the problem i the wasm area.

This one doesn't implement execute function which seems to explain where the error comes from, 
https://github.com/simolus3/sqlite3.dart/blob/main/sqlite3/lib/src/wasm/sqlite3.dart
class WasmSqlite3 implements CommmonSqlite3 {

BUT there is WasmDatabase extends CommonDatabase which creates the execute function. 
https://github.com/simolus3/sqlite3.dart/blob/main/sqlite3/lib/src/wasm/database.dart
@internal
class WasmDatabase extends CommonDatabase {

I cannot do more :) ...

**Comment by simolus3** [comment]
> This one doesn't implement execute function which seems to explain where the error comes from,

Maybe that's the misunderstanding? `execute()` is a method on a sqlite3 _database instance_. The top-level `WasmSqlite` is only used to open those database and doesn't have an `execute` method itself.

**Comment by brilliapps** [comment]
Not correcting code, just showing what i did, kind of from the beginning, which is an operation on an instance of a database as i think i see, and the error is not only during compilation but also in Visual Express, in the console i saw it is an instance of WasmSqlite3, and maybe by accident you said about WasmSqlite top-level class but you may have had in mind WasmDatabase i was talking about, please, see exactly the pieces of codes with classess i was mentioning and what they extend (excuse my ignorance i imagined there are couple of peaople working on the code, or maybe i have something uniquely broken even after complete manual replacement of flutter/dart sdk, cleaning, testing on a separate simple project):
 
`
    final response = await http.get(Uri.parse('sqlite3.wasm'));
    final fs = await IndexedDbFileSystem.open(
        dbName:
            'test' );

    WasmSqlite3 db = await WasmSqlite3.load(
        response.bodyBytes, SqliteEnvironment(fileSystem: fs));



    db.execute('''
        CREATE TABLE tests (
          id INTEGER NOT NULL PRIMARY KEY,
          name TEXT NOT NULL
        );
        ''');
`

**Comment by brilliapps** [comment]
Ok i know what happened. I try to be type-strict giving/hinting expected types wherever i can for future code readers. But by putting WasmSqlite3 db = .... i "told" what the db must be of type WasmSqlite3, but the db is of different type (i guess). 
So not tested yet, but in Visual Express i see it is ok:
So quickly this
    WasmSqlite3 db = ...
changed to
    dynamic db = ....

Sorry :)

**Comment by brilliapps** [comment]
I reedited the previous comment so it is valid and deleted one. I too quickly wrote i had success with the stuff but the same problem remains.
