### ISSUE TITLE
Get the last row "ID" in insert using prepare

### ISSUE THREAD

**Issue by andre-ab** [simolus3/sqlite3.dart#138]
I can't find it in the documentation
How to get the last row "ID" in insert using prepare?

**Comment by simolus3** [comment]
After you ran a prepared statement containing an insert, you can use `lastInsertRowId` to get its rowid as well. Simply preparing a statement will not alter the last row id, you need to execute this statement for it to have any effect.

If you want to get the last insert rowid _in_ a prepared statement, you can use something like `prepare('SELECT last_insert_rowid()')`.
