### ISSUE TITLE
DuckDB bindings

### ISSUE THREAD

**Issue by gilice** [simolus3/sqlite3.dart#141]
DuckDB, a popular data analysis DBMS exposes [sqlite_api_wrapper](https://duckdb.org/docs/api/c/overview), which is an interface to DuckDB that is designed to be very similar to the sqlite3 C api.

Thus it could be probably made to work with sqlite3 without major modifications to the code.

**Comment by simolus3** [comment]
While it sounds like something that's doable, I want to be transparent and say that adding support for other sqlite3-like APIs is not a priority for me.

PRs for this are welcome, and I'm happy to help if someone wants to add DuckDB support to this package, but I don't have the resources to implement, maintain and test these bindings.

**Comment by gilice** [comment]
hey Simon,
sorry if it wasn't clear. I opened this issue as I want to work on it, but
wanted to check it anyone did it before.
we can close this issue as not planned not to clutter up the repo, but I'd
still like this communication channel to be open since You probably know
the code the best.

**Comment by simolus3** [comment]
I'm not aware of any work on this being done already.

> we can close this issue as not planned not to clutter up the repo

Sure. Maybe a good way to start working on this is to do this in a fork? We can always check the impact of the changes and if there's a way to integrate parts of them in this repository.

> but I'd still like this communication channel to be open

Absolutely, feel free to ask if you have any questions about the FFI layer or other internals of the `sqlite3` Dart package.

**Comment by gilice** [comment]
I looked into it. The API wrapper is okay.
A few caveats:
- it does support open v3, but not prepare v3 so I had to comment out that code
- error handling is a mess since there isn't any `sqlite3_extended_result_codes` or `sqlite3_errstr` support.
