### ISSUE TITLE
NaN causes crash

### ISSUE THREAD

**Issue by Erhannis** [simolus3/sqlite3.dart#142]
sqlite3 1.9.1
sqlite3_flutter_libs 0.5.13

If I try to do e.g.
```
db.execute("insert or replace into BLAH (value) values (?)", [x]);
```
(slightly cleaned up from real code)
it works fine for normal numbers, `double.infinity`, `double.negativeInfinity`, `double.maxFinite`, and `double.minPositive`, but NOT for `double.nan`.  (Cleaned) error log:
```
Error in sink: SqliteException(1299): NOT NULL constraint failed: BLAH.value, constraint failed (code 1299)
  Causing statement:             insert or replace into BLAH (
                value
            ) values (
                ?
            ) #0      throwException (package:sqlite3/src/ffi/impl/exception.dart:38:3)
#1      PreparedStatementImpl._execute (package:sqlite3/src/ffi/impl/statement.dart:91:7)
#2      PreparedStatementImpl.execute (package:sqlite3/src/ffi/impl/statement.dart:68:5)
#3      DatabaseImpl.execute (package:sqlite3/src/ffi/impl/database.dart:139:14)
(stack trace continues into my code)
```

It seems to me that (ideally) all possible values of `double` would translate to/from the database, with NULL remaining separate.  Is this a thing that can be fixed in your code, or do I need to petition somebody else?  (Some sqlite dll, for instance.)  Thanks!

**Comment by simolus3** [comment]
Interesting report, thanks! Disallowing NaN values happens [inside sqlite3](
https://github.com/sqlite/sqlite/blob/74e6e30358e1e989ba204558b0e9e688edffd98f/src/vdbemem.c#L961-L971), so I'm afraid there is nothing we can do about that. sqlite3 also doesn't allow `NaN` for numeric literals, so I don't think there's a workaround we could apply either.

I couldn't find a mention for this in the documentation, but I also didn't look very hard. They probably have a reason for this, but you could ask on the sqlite forums to see if there's a way to eventually support NaNs.

**Comment by Erhannis** [comment]
Bummer.  And the infinities get (correctly) converted in sqlite3?  (As opposed to it being something you were able to tack on in the wrapper.)

**Comment by simolus3** [comment]
Yeah, we just call `sqlite3_bind_double` which supports infinity and negative infinity just fine. Maybe NaN is excluded because of the peculiar comparison properties that make it similar to `NULL` in SQL.
