### ISSUE TITLE
Spellfix extension on android

### ISSUE THREAD

**Issue by hamzaj9** [simolus3/sqlite3.dart#152]
Hello,

I just want to know how exactly can i use spellfix extension on android?
i noticed that on iOS we should use:
```sqlite3.ensureExtensionLoaded(SqliteExtension.staticallyLinked('sqlite3_spellfix_init'));```

but what about android?

thank you

**Comment by simolus3** [comment]
On iOS, you also need to add a dependency on `sqlite3/spellfix` to compile the module. On Android, we unfortunately can't really have a mechanism to make individual extensions available as modules.

You'd have to use the [NDK](https://developer.android.com/ndk) to compile the [spellfix](https://www.sqlite.org/src/finfo?name=ext/misc/spellfix.c) extension as an additional shared library that you ship with your app. You can take a look at [what I'm doing](https://github.com/simolus3/sqlite-native-libraries/tree/master/sqlite3-native-library) to compile sqlite3 on Android as a starting point. Then, you'd need to load that library and then use [`SqliteExtension.inLibrary`](https://pub.dev/documentation/sqlite3/latest/sqlite3/SqliteExtension/SqliteExtension.inLibrary.html) to load it.
