### ISSUE TITLE
any small example of how to use sqlcipher on flutter

### ISSUE THREAD

**Issue by mohammedX6** [simolus3/sqlite3.dart#156]

**Comment by simolus3** [comment]
I've added an example to the readme, does that help? https://github.com/simolus3/sqlite3.dart/tree/main/sqlcipher_flutter_libs#using-this-package

**Comment by mohammedX6** [comment]
I have sqlite database using sqlite3 and flutter sqlcipher how i can encrypt my database using a secret key,
btw I don't find anything there

**Comment by simolus3** [comment]
> how i can encrypt my database using a secret key

You can view the API exposed through SQL [here](https://www.zetetic.net/sqlcipher/sqlcipher-api/), the `key` pragma is also used in the example.
