### ISSUE TITLE
Error to load database on android

### ISSUE THREAD

**Issue by ousvat** [simolus3/sqlite3.dart#164]
**Describe the bug**

When I tried to make a query to the database, I have this error: 

```
Invalid argument(s): Failed to load dynamic library '/data/data/com.wattapps.iplanto/lib/libsqlite3.so': dlopen failed: library "/data/data/com.wattapps.iplanto/lib/libsqlite3.so" not found #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
I/flutter (15362): simolus3/drift#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
I/flutter (15362): simolus3/drift#2      _defaultOpen (package:sqlite3/src/ffi/load_library.dart:40:29)
I/flutter (15362): simolus3/drift#3      OpenDynamicLibrary.openSqlite (package:sqlite3/src/ffi/load_library.dart:127:12)
I/flutter (15362): simolus3/drift#4      sqlite3 (package:sqlite3/src/ffi/api.dart:15:39)
I/flutter (15362): simolus3/drift#5      _NativeDelegate.openDatabase (package:drift/native.dart:204:12)
I/flutter (15362): simolus3/drift#6      Sqlite3Delegate.open (package:drift/src/sqlite3/database.dart:61:19)
I/flutter (15362): simolus3/drift#7      DelegatedDatabase.ensureOpen.<anonymous closure> (package:drift/src/runtime/executor/helpers/engines.dart:424:22)
I/flutter (15362): <asynchronous suspension>
```
There is how I open the database: 
```
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    return NativeDatabase(await getDatabaseFile());
  });
}

```

This issue appear only on android. On iOS everything is fine.

**Comment by simolus3** [comment]
Is this on all Android versions? There's a [known workaround](https://github.com/simolus3/sqlite3.dart/tree/main/sqlite3_flutter_libs#problems-on-android-6) for this on really old Android versions, I've not seen this error happening on newer Android versions though.

And just to be sure, you have a dependency on `sqlite3_flutter_libs`?

**Comment by ousvat** [comment]
> Is this on all Android versions? There's a [known workaround](https://github.com/simolus3/sqlite3.dart/tree/main/sqlite3_flutter_libs#problems-on-android-6) for this on really old Android versions, I've not seen this error happening on newer Android versions though.
> 
> And just to be sure, you have a dependency on `sqlite3_flutter_libs`?

@simolus3 This appears on Android 13

**Comment by ousvat** [comment]
> I can't reproduce this with a new project that I'm running on an emulator, do you have a simple project with this issue that you could share?

The issue was that I miss adding the `sqlite3_flutter_libs` package to `pubspec`.

Thanks anyway!
