### ISSUE TITLE
How to upgrade an existing database to add new column

### ISSUE THREAD

**Issue by isaanyoha** [simolus3/sqlite3.dart#166]
Hi, please how to upgrade an existing database to add new column to a particular table without deleting the database, and also not add the column next time if it already exist in the table?

**Comment by simolus3** [comment]
Hi, this is what [database migrations](https://drift.simonbinder.eu/docs/advanced-features/migrations/) are for.

Basically, you assign a number to each version of your schema (which tables and columns there are). After you've added the column to the table, you increment the value returned by the `schemaVersion` getter in your database and write a migration that calls `addColumn` in its `onUpgrade` callback. The documentation page I've linked has an example for that, let me know if that doesn't clear things up.
