### ISSUE TITLE
Copying data from one database to another one using ATTACH

### ISSUE THREAD

**Issue by mohammedX6** [simolus3/sqlite3.dart#168]
How I can do it here ? 
more info [here](https://stackoverflow.com/questions/2359205/copying-data-from-one-sqlite-database-to-another)

**Comment by simolus3** [comment]
I don't understand the question, you can run the `ATTACH` command and any other step you need via [execute](https://pub.dev/documentation/sqlite3/latest/sqlite3.wasm/CommonDatabase/execute.html). There's nothing special that this package would introduce.

But perhaps the [backup](https://pub.dev/documentation/sqlite3/latest/sqlite3/Database/backup.html) API is more efficient when you want to copy an entire database?

**Comment by mohammedX6** [comment]
thanks for explaining
