### ISSUE TITLE
sqlite3 wasm up-to-date working example

### ISSUE THREAD

**Issue by brilliapps** [simolus3/sqlite3.dart#169]
Hello, on this page https://pub.dev/packages/sqlite3 where we can find information about the latest sqlite3 package we can find code for web (WebAssembly, wasm). Because as i understand the example there at the moment of writing of this issue is out-of-date i was forced to figure out a FULL working get-started example and propose to update the information on the pub.dev page, of course not with the flawed example of mine.

First, how it is now and then my proposal:

```dart
import 'package:http/http.dart' as http;
import 'package:sqlite3/common.dart';
import 'package:sqlite3/wasm.dart';

Future<WasmSqlite3> loadSqlite() async {
  final fs = await IndexedDbFileSystem.open('my_app');

  return await WasmSqlite3.loadFromUrl(
      Uri.parse('sqlite.wasm'),
      environment: SqliteEnvironment(fileSystem: fs),
  );
}
```

And the full proposal which was done successfully with sqlite3 v. 2.0.0, flutter 3.10.4, windows 11, device chrome, it uses print method so no need to use --debug option. hot reload and and hot restart (r, and R) insert another (second, third...) row to an existing database, so it works.). This is the full main.dart file modified after flutter create command.

```dart
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:sqlite3/wasm.dart';

void main() async {
  final response = await http.get(Uri.parse('sqlite3.wasm'));

  // The [IndexedDbFileSystem] class is descentant of [VirtualFileSystem] which will be needed in a while
  IndexedDbFileSystem fs = await IndexedDbFileSystem.open(dbName: 'test');
  WasmSqlite3 wasmSqlite3Object = await WasmSqlite3.load(response.bodyBytes);

  // So here as a param wee need to pass the mentioned [VirtualFileSystem] object and [IndexedDbFileSystem] is descentant of the class [VirtualFileSystem]
  wasmSqlite3Object.registerVirtualFileSystem(fs);

  dynamic db = wasmSqlite3Object.open('testsname.sqlite3');

  db.execute('''
      CREATE TABLE IF NOT EXISTS artists (
        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        counter INTEGER NOT NULL,
        name TEXT NOT NULL
        );
        ''');

  db.execute('''
      INSERT INTO "artists" ("counter", "name") VALUES (5,	'Name Surname');
  ''');

  ResultSet artists = db.select('''
      SELECT * FROM artists;
  ''');

  print(artists);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

The example can be also found here https://github.com/brilliapps/sqlite3-2.0.0-library-wasm-example--flutter-dart-/tree/main

**Comment by simolus3** [comment]
You're right, the web example was not in a great state. I've improved the situation a bit in 616cde285975b122251baace9bf778fe61f3918a by adding a readme and bringing back an example that doesn't require workers.

The philosophy of this package is to not do too much setup work by itself - it's a fairly lightweight and direct wrapper around sqlite3. On native platforms that's not much of an issue because sqlite3 doesn't require much of a setup there. On the web however, the situation is more complicated. Realistically you'll probably want to host the database in a worker instead of accessing it synchronously. Packages like [sqflite](https://pub.dev/packages/sqflite_common_ffi_web) or [drift](https://drift.simonbinder.eu/web/) can reduce the setup work by wrapping this package on the web. I recommend using them if that works for you.

**Comment by brilliapps** [comment]
Thank you for your response and steps taken. I'll need to analyse all options available (with drift, sqlitej, workers - this would be a good idea, however for now i am trying to do everything in fully crossplatform dart, so want to use asynchronous programming for now using the "event loop" which can be seen in one of my still early stage project, but the workers approach now seem more attractive).

**Comment by simolus3** [comment]
> which can be seen in one of my still early stage project

FWIW the `sqlite3-2.0.0-library-wasm-example--flutter-dart` link you've included in the issue description doesn't seem to work.

> if i needed to use any platform special approach like js, windows api/com32

[This is all the platform-specific code you need](https://github.com/simolus3/drift/tree/develop/examples/app/lib/database/connection) when using drift, you can write it all in Dart without resorting to manual JS.
The only distinction is between native/web. You can similarly use conditional imports with the two sqflite ffi packages.

**Comment by brilliapps** [comment]
Once again thank you for your feedback.
With other readers in mind i try to explain what to do. First, i don't know now why not all folder structure was sent via git/push. But it is ok. While this is not the "early stage project" (i meant the project "Condition", didn't want to promote myself) the code probably doesn't work because this is not full directory of the project and this is just about the lib/main.dart file and pubspec.yaml file with the added newest versions of http package (1.0.0) and sqlite3 (2.0.0) (as of 25.06.2023). First of all someon probably copy the compiled sqlite3.wasm file to the web folder, according to your directions. As far as i remember, the file can be found on the releases page of your project.
To use the main.dart file someone might create new project via flutter create which create the famous counter app, enable chrome (if he/she needs to), just replace the main.dart file with that from my project, copy the mentioned sqlite3.wasm file to the web folder, add both http and sqlite3 packages into the pubspec.yaml file, and run the app via flutter run -d chrome or flutter run -d chrome --debug. If it doesn't help i am not aware at the moment what the problem might be.
