### ISSUE TITLE
XCode15 .pub-cache/hosted/pub.dev/sqlite3_flutter_libs-0.5.17/macos/Classes/Sqlite3FlutterLibsPlugin.h:1:9: fatal error: 'FlutterMacOS/FlutterMacOS.h' file not found

### ISSUE THREAD

**Issue by luohao123** [simolus3/sqlite3.dart#182]
.pub-cache/hosted/pub.dev/sqlite3_flutter_libs-0.5.17/macos/Classes/Sqlite3FlutterLibsPlugin.h:1:9: fatal error: 'FlutterMacOS/FlutterMacOS.h' file not found

**Comment by simolus3** [comment]
This still works for me, which Flutter version are you using or did you remember doing anything before this started breaking?

**Comment by luohao123** [comment]
sorry my mistake.
