### ISSUE TITLE
Adding support for SpatiaLite?

### ISSUE THREAD

**Issue by coogle** [simolus3/sqlite3.dart#183]
Curious, any plans to add support for SpatiaLite?

[SpatiaLite](https://www.gaia-gis.it/fossil/libspatialite/index)

**Comment by simolus3** [comment]
Not directly, no.

SpatiaLite doesn't require any new C interfaces, it is commonly used through virtual tables and custom functions which are available through the sqlite3 package by just running SQL queries.

I don't actually know whether SpatiaLite is a full sqlite3 fork or a loadable extension, but I don't have the capacity to distribute it via something like `spatialite_flutter_libs`. But if you find another way to include SpatiaLite libraries, you can likely use it with this package.
