### ISSUE TITLE
Sqlite3 2.0.0, Web, wasm, .select causing dart uncatchable error (or exception?)

### ISSUE THREAD

**Issue by brilliapps** [simolus3/sqlite3.dart#184]
As in the title, the native version allows for catching and i can perform other sql queries. I guess some actions into a Worker (i know there is an example code for that) or to the main index.html/js directly and tring to handle exception in js and then send info to dart is a temporary solution, but for now wanted report the problem. 

The sql statement causing accepted exception (again, it can fail it's fine):
SELECT count(*) FROM tablename;

dart code: db.select(query) ;

error thrown:
Error: SqliteException(1): while preparing statement, no such table: tablename, SQL logic error
(code 1)
  Causing statement:           SELECT count(*) FROM tablename;

The same possibly might be for the execute statement, not tested yet.

**Comment by simolus3** [comment]
I'm not sure if I understood the problem correctly. When not using workers, I can catch exceptions just fine (with e.g. this patch to `example/main.dart`):

```patch
diff --git a/sqlite3/example/web/main.dart b/sqlite3/example/web/main.dart
index 3bfede9..7a2da32 100644
--- a/sqlite3/example/web/main.dart
+++ b/sqlite3/example/web/main.dart
@@ -18,12 +18,18 @@ Future<void> main() async {
 
     sqlite3.open('/database')
       ..execute('pragma user_version = 1')
-      ..execute('CREATE TABLE foo (bar INTEGER NOT NULL);')
+      ..execute('CREATE TABLE IF NOT EXISTS foo (bar INTEGER NOT NULL);')
       ..execute('INSERT INTO foo (bar) VALUES (?)', [3])
       ..dispose();
 
     final db = sqlite3.open('/database');
     print(db.select('SELECT * FROM foo'));
+
+    try {
+      db.select('select * from table_that_does_not_exist;');
+    } on SqliteException {
+      print('caught exception!');
+    }
   });
 
   startOpfs.onClick.listen((_) async {
```

This prints `caught exception` for me.

**Comment by brilliapps** [comment]
Thank you for your answer, it is exactly as you said. Sorry for bothering you. While it is not related to the sqlite3 package, i may need some time to find out why a file importing a file that uses the package didn't throw the exception correctly but in a file that imports the wasm package and directly uses the db (db.open) object the exception can be catched. So just wanted inform you that it's not that i haven't checked it more thoroughly before posting. Summing up, i was sort of wrong, closing the issue and may post some explanation if it will be relevant.

**Comment by brilliapps** [comment]
Yeah i confirm it looks like the exception can be catched in a dart file that opened the db and got you the db object working but in another dart file that has an abstract class which serves as a wrapper with some shared methods that is extended by native and web version, so that abstract class in another file cannot catch the exception for web. Don't know when i will adress the problem and i bear in mind to give some update if it is useful. If it's not my fault, and 99,9% my error, it might hyphothetically be related to dart language web implementation inconsistency with the native version.

**Comment by brilliapps** [comment]
I found out that the error is catchable. Yet still i need to investigate more. To simplify, code with description.

First a line from a method below that i understand works for native, not for web when throwing exception:

completer.complete(db.select(query));

And a piece of code with the line at the end that causes the exception to be catchable ALSO for web:

     dynamic result;
      try {
        result = db.select(query);
      } catch (e) {
        completer.completeError(e.toString());
        return;
      }
      completer.complete(result);


This is an entire WRAPPER SELECT method that is called (now, we know what db means):

  @override
  Future<List<Map<String, dynamic>>?> select(String query) {
    Completer<List<Map<String, dynamic>>?> completer =
        Completer<List<Map<String, dynamic>>?>();
    debugPrint('db wrapper select method 1 we are here. query is $query');
    scheduleMicrotask(() {
      debugPrint('db wrapper select method 2');
// !!! catchable by web and native
      try {
        db.select('select * from table_that_does_not_exist;');
      } catch (e) {
        print('4caught exception!');
      }
      /// catchable by native NOT by web
      completer.complete(db.select(query));
      debugPrint('db wrapper select method 3');
    });
    return completer.future;
  }


And this is example code calling the WRAPPER METHOD that now throws catchable excepiton both for web and native:

        bool isAppDbinited = true;

        try {
          var select_is_debinited = await _db.select('''
          SELECT count(*) FROM tablename;
          ''');
        } catch (e) {
          debugPrint(
              'table doesn\'t exist');
          isAppDbinited = false;
        }


So still seems like it could be that web implementation of probably Completer/Future may be a little bit not exactly the same as in native. But it is easy to repair as i see now, and might be not aware of something else because with much stuff of different kind it's easy not to see something important.

**Comment by simolus3** [comment]
The problem is likely that `db.select` throws synchronously, whereas methods returning a future are in many cases expected to never throw, and instead return a future completing with an error. The completer hack works, but you can do this more easily with:

```dart
  @override
  Future<List<Map<String, dynamic>>?> select(String query) {
    return Future(() => db.select(query));
  }
```

or, even easier:

```dart
  @override
  Future<List<Map<String, dynamic>>?> select(String query) async {
    return db.select(query);
  }
```

These should both be able to report the error into the future.

**Comment by brilliapps** [comment]
Thanks! No time now, need to look at it later, just wanted notice that native let's you through :) .

**Comment by brilliapps** [comment]
Yeah, it works too and i complicate much and much different syntaxes in one language :) It probably could be even a tiny little bit shorter :) :)
Future<List<Map<String, dynamic>>?> select(String query) => Future(() => db.select(query));

So i can go ahead with my code.
