### ISSUE TITLE
Upgrade to dart:ffi 0.3.0-nullsafety.1

### ISSUE THREAD

**Issue by gibutm** [simolus3/sqlite3.dart#19]
If the plugin is used with dart:ffi 0.3.0-nullsafety.1 the following errors are seen

> ../../../flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-0.1.9-nullsafety.2/lib/src/impl/database.dart:46:19: Error: Method not found: 'allocate'.
>     final outDb = allocate<Pointer<sqlite3>>();
>                   ^^^^^^^^
> ../../../flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-0.1.9-nullsafety.2/lib/src/impl/database.dart:100:22: Error: The method 'allocate' isn't defined for the class 'DatabaseImpl'.
>  - 'DatabaseImpl' is from 'package:sqlite3/src/impl/implementation.dart' ('../../../flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-0.1.9-nullsafety.2/lib/src/impl/implementation.dart').
> Try correcting the name to the name of an existing method, or defining a method named 'allocate'.
>     final errorOut = allocate<Pointer<char>>();
>                      ^^^^^^^^
> ../../../flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-0.1.9-nullsafety.2/lib/src/impl/database.dart:134:21: Error: The method 'allocate' isn't defined for the class 'DatabaseImpl'.
>  - 'DatabaseImpl' is from 'package:sqlite3/src/impl/implementation.dart' ('../../../flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-0.1.9-nullsafety.2/lib/src/impl/implementation.dart').
> Try correcting the name to the name of an existing method, or defining a method named 'allocate'.
>     final stmtOut = allocate<Pointer<sqlite3_stmt>>();
>                     ^^^^^^^^
> ../../../flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-0.1.9-nullsafety.2/lib/src/ffi/memory.dart:29:18: Error: Method not found: 'free'.
>   void free() => ffi.free(this);
>                  ^^^^
> ../../../flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-0.1.9-nullsafety.2/lib/src/ffi/memory.dart:33:15: Error: Method not found: 'allocate'.
>   final ptr = ffi.allocate<Uint8>(count: bytes.length + additionalLength);

Is a release planned to support this? Is there a branch that can be pointed to resolve this before it is published?

**Comment by simolus3** [comment]
Did you get this from a regular `pub get`? You're using dependency overrides, right?

The current version on `master` should support the latest version of `package:ffi`, I just didn't release it yet because there's no Dart beta compatible with it:

```yaml
dependency_overrdides:
  sqlite3:
    git:
      url: git@github.com:simolus3/sqlite3.dart.git
      path: sqlite3/
```

**Comment by simolus3** [comment]
Actually, I just published version `0.1.10-nullsafety.0` which should work. Let me know if you run into any issues with that, thanks!

**Comment by kuhnroyal** [comment]
Had the same issue and updated but this collides with nullsafety versions of `meta`.

**Comment by kuhnroyal** [comment]
Well nvm I can override this, the Flutter beta version is not yet using `1.3.0`.

**Comment by gibutm** [comment]
Thanks for the quick reply and the quicker fix )

> Actually, I just published version `0.1.10-nullsafety.0` which should work. Let me know if you run into any issues with that, thanks!

Tried it out, as @kuhnroyal pointed out, package versions for meta and collection cannot be resolved unless explicitly they are overridden to   meta: 1.3.0-nullsafety.6 and  collection: 1.15.0-nullsafety.5

I tried the dependency override and it seems to be stable with no side effects.

Would be great if an update could be published.

**Comment by simolus3** [comment]
In general I try to move towards the stable null-safety versions where that's possible, it makes it much easier for me since I don't need to worry about further changes they might squeeze into pre-releases.

Flutter also uses those versions on its `master` channel, so unfortunately I think you'll need to deal with the dependency overrides until that rolls into beta.

**Comment by kuhnroyal** [comment]
@simolus3 I agree, you have the latest versions as dependencies, @gibutm Just use overrides when you are on the beta channel.

**Comment by kuhnroyal** [comment]
@gibutm The new Flutter beta `1.26.0-17.4.pre` seems to solve these problems.
