### ISSUE TITLE
how to get table-count of db, through `SQLite3.exec("SELECT count(*) FROM sqlite_schema WHERE type = 'table'").getInt()`

### ISSUE THREAD

**Issue by gintominto5329** [simolus3/sqlite3.dart#196]
hi,

I want to get the number of all the tables, in the whole db,
How may I?

thanks

**Comment by simolus3** [comment]
You can use `select`, which returns a list of rows. Since there will only be one, use `.single` and then call `values[0]` to access columns by their index.

```dart
final amountOfTables = db
    .select("SELECT count(*) FROM sqlite_schema WHERE type = 'table'")
    .single
    .values[0];
```
