### ISSUE TITLE
Implement a `pkg:realm:Realm:write` like method to `Database`, which calls the passed function in a transaction, commit on success, otherwise rollback

### ISSUE THREAD

**Issue by gintominto5329** [simolus3/sqlite3.dart#197]
Hi

MongoDB's Realm package, supports a [`write`](https://pub.dev/documentation/realm/latest/realm/Realm/write.html) method, on its `Database` equivalent, implementation of which is:
```dart
T write<T>(T Function() writeCallback) {
  final transaction = beginWriteTransaction();

  try {
    T result = writeCallback();
    transaction.commit();
    return result;
  } catch (e) {
    transaction.rollback();
    rethrow;
  }
}
```

thanks

**Comment by simolus3** [comment]
We won't support a high-level transaction interface in this package, see #198. You could take a look at [this package](https://pub.dev/packages/sqflite_common_ffi) which wraps this package to support transaction callbacks.
