### ISSUE TITLE
Migrate away from `elementAt` for Dart 3.3

### ISSUE THREAD

**Issue by dcharkes** [simolus3/sqlite3.dart#205]
`elementAt` has been deprecated as of Dart 3.3 and should be replaced by `operator +`.

Valid SDK bound for using `operator +`: `"version:3.3.0-279.1.beta"`.

Context:

* https://github.com/dart-lang/sdk/issues/54250

**Comment by simolus3** [comment]
Thanks for the heads-up! Is this also preventing the change from landing in g3 or can this wait until the stable 3.3 release?

**Comment by dcharkes** [comment]
No hurry, there might be other reasons why we need to postpone the removal of `elementAt`.
