### ISSUE TITLE
sqlcipher_flutter_libs adding libraries for other platforms in Android build

### ISSUE THREAD

**Issue by velten-dev** [simolus3/sqlite3.dart#209]
I was trying to see why my apk files were so large, so I did some profiling using the command
```flutter build apk --analyze-size --target-platform=android-arm64```

I was surprised to find that there were multiple copies of libsqlcipher.so in the apk bundle. Even though the build specified only arm64-v8, I see libsqlcipher.so in also x86_64, x86, and armeabi-v7a. Is there something I am missing? These extra libraries are adding almost 15 MB to an apk which would otherwise be about 25 MB. 

![image](https://github.com/simolus3/sqlite3.dart/assets/101442122/1a7b5f7e-f3fe-4ac5-80c1-770362293eef)

**Comment by simolus3** [comment]
I don't fully understand `--target-platform` is implemented in the CLI tool, but it seems to set the `targetPlatform` project property read in [this build file](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy). I've only skimmed the references there, but it seems to only apply that to the Flutter engine and the compiled Dart application, it doesn't apply an NDK filter that would filter dependencies. So I'm not sure if there's much this package could do about that.

Would it be an alternative to use `--split-per-abi` or to create an app bundle and split that using `bundletool`?

**Comment by velten-dev** [comment]
Ok, yes it seems that when not splitting on abi or using the bundle tool, it bundles all of the libraries together. When I split the application per abi, I see the following apk sizes:

```
flutter build apk --split-per-abi --no-tree-shake-icons --target-platform android-arm,android-arm64

Running Gradle task 'assembleRelease'...                           13.1s
✓  Built build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk (23.8MB).
✓  Built build/app/outputs/flutter-apk/app-arm64-v8a-release.apk (27.4MB)
```

However, when not split, I see the following:

```
flutter build apk --no-tree-shake-icons --target-platform android-arm,android-arm64

Running Gradle task 'assembleRelease'...                           10.1s
✓  Built build/app/outputs/flutter-apk/app-release.apk (60.2MB).
```

The extra 10 MB of size seems to come from the bundling of the x86 versions of the sqlcipher libraries. I suppose my workaround for now is to publish the ap split per abi, but it would be nice to have the size reduced and be able to publish a mono-arm built apk.
