### ISSUE TITLE
SQLCipher does not work on Windows.

### ISSUE THREAD

**Issue by kssce** [simolus3/sqlite3.dart#214]
My operating system is windows 11 home edition and powershell 7 is also installed.
I did not install or configure Openssl separately.
I installed visual studio 2022 community for flutter development, and have been running the app normally on Windows.
The dependencies are as follows:
flutter: 3.19.1
drift: ^2.16.0
drift_dev: ^2.16.0
sqlite3:^2.4.0
sqlcipher_flutter_libs: ^0.6.1
Android, iOS and macOS are working. On windows I get the following errors:

```
CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.27/Modules/FindOpenSSL.cmake:668 (find_package_handle_standard_args)
  flutter/ephemeral/.plugin_symlinks/sqlcipher_flutter_libs/windows/CMakeLists.txt:27 (find_package)
```

**Comment by simolus3** [comment]
>  I did not install or configure Openssl separately.

This package is just exposing the existing build scripts from SQLCipher, which requires an existing crypto library. On other systems, SQLCipher is able to use native crypto libraries, but on Windows it requires OpenSSL.

So I think there's not too much we can do here, you'll probably have to install OpenSSL.
