### ISSUE TITLE
NoSuchMethodError: method not found: 'instantiateStreaming'

### ISSUE THREAD

**Issue by matehat** [simolus3/sqlite3.dart#220]
On Safari 14.1.2, a client threw an error like this:

```
NoSuchMethodError: method not found: 'instantiateStreaming' (self.WebAssembly.instantiateStreaming is not a function. (In 'self.WebAssembly.instantiateStreaming(a,o)', 'self.WebAssembly.instantiateStreaming' is undefined))
```

It seems expected as this API is [not available on that version of Safari](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiateStreaming_static#browser_compatibility).

Is there a way to fallback to an alternative Drift implementation on clients that are too old to support the current version of the DB?

**Comment by matehat** [comment]
Nevermind, just found this [other issue](https://github.com/simolus3/sqlite3.dart/issues/187).

**Comment by simolus3** [comment]
I think we can't support older Safari versions. In addition to `instantiateStreaming`, another problem is that older browsers don't support calling WebAssembly functions with a 64bit parameter or return value, but this is something we need in lots of places for sqlite3.
So unfortunately I'll have to close this as well, the complexities necessary to achieve partial support on older browsers aren't worth it.
