### ISSUE TITLE
2.4.1 error when compiling for iOS

### ISSUE THREAD

**Issue by hermannbjornsson** [simolus3/sqlite3.dart#223]
I get the following error when compiling for 
Error (Xcode): ../../../.pub-cache/hosted/[pub.dev/sqlite3-2.4.1/lib/src/ffi/bindings.dart:341:14](http://pub.dev/sqlite3-2.4.1/lib/src/ffi/bindings.dart:341:14): Error: The operator '+' isn't defined for the class 'Pointer<Uint8>'.

My temporary solution is to revert back to 2.4.0

**Comment by qwertylolman** [comment]
i'm only have transitive dependency on sqlite package and still got this error...

**Comment by hermannbjornsson** [comment]
> i'm only have transitive dependency on sqlite package and still got this error...

Same here, however if you add
```
sqlite3: '2.4.0'
```
in your main application pubspec.yaml file it should override any packages allowing for higher versions to be pulled as long as  2.4.0 is compatible

**Comment by sebastianolaru3008** [comment]
I was able to reproduce this bug also by running on the `flutter test` command on a project that uses sqlite3 as transitive dependency.

**Comment by simolus3** [comment]
Thank you for the report, and apologies for the inconvenience. Version `2.4.1` requires Dart 3.3 or later, but has Dart 3.2 as a lower bound in its pubspec. If you use that version with an older Dart/Flutter SDK, you'll see this error.

Continuing to use version 2.4.0 is fine, I have retracted version 2.4.1 from pub.dev and published 2.4.1+1 which has the correct SDK bound in its pubspec.
