### ISSUE TITLE
Please update SQL cipher to 4.5.7

### ISSUE THREAD

**Issue by Viditkhanna** [simolus3/sqlite3.dart#227]
The native library SQLCipher has been updated to [4.5.7](https://github.com/sqlcipher/sqlcipher/issues/501) and it includes the Apple Privacy Manifest file which is necessary so that new builds for flutter app can be accepted by Appstore after May 1st 2024.

For reference
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by simolus3** [comment]
Thanks for the heads-up, done!
