### ISSUE TITLE
[QUESTION ] Should I closing db object with finaliser?

### ISSUE THREAD

**Issue by Krzysztof-Lempicki** [simolus3/sqlite3.dart#235]
# Context

I have one singleton class where I store one `database` instance  throughout the application's lifespan.

```
StorageService {
  
  final Database _db = _initDb();
```

# Questions

a) is this correct that I am using same object all the time?
b) should I close it before application ends or can I rely on flutter that it will do this under the hood?

**Comment by simolus3** [comment]
Opening a database once and then not closing it is not a problem nor a leak if you really need it during the entire span of your application.
SQLite databases don't need to be closed explicitly, all the data is saved when a statement completes. You release some resources when disposing a database, but again what's the point if you need the database while the application is active.

You should close databases when you're done with them and your application will stay active for longer. But even that's not critical as this package also provides a finalizer for that.
