### ISSUE TITLE
Enable SQLITE_ENABLE_DBSTAT_VTAB

### ISSUE THREAD

**Issue by FaFre** [simolus3/sqlite3.dart#237]
SQLite has this cool feature to get insights into the used disk space of content (https://www.sqlite.org/dbstat.html).

One of the use cases would be communicating the size of e.g. a caching table to the user, so he can decide to clear up some space, or base some logic on that.

For using this feature, it is required to enable SQLITE_ENABLE_DBSTAT_VTAB compile time option. I think there will be no performance impact in general, as the table is always created on the fly, only during the actual select of dbstat. Also the impact on the file size of the sqlite lib should be very small, as the implementation is very simple.

Do you think it will be feasible to activate this? I can offer to contribute some PR to enable this (with exception of ios/macos)

**Comment by simolus3** [comment]
I agree, this would be nice to have - it's included in the default build and doesn't cost much. It's a bit of a hassle to change the flags in the current setup, but if you get started with a wasm/linux/windows PR I can get the iOS/macOS/Android side prepared which requires me to re-release the native library.

**Comment by simolus3** [comment]
Thanks again for your contribution, I've just released this as `sqlite3_flutter_libs` version `0.5.24`.

**Comment by FaFre** [comment]
Great! Thank you a lot :)
