### ISSUE TITLE
Flutter Web WASM support

### ISSUE THREAD

**Issue by zs-dima** [simolus3/sqlite3.dart#239]
flutter build web --wasm

Leads to the Error
/home/flutter/.pub-cache/hosted/pub.dev/sqlite3-2.4.2/lib/src/wasm/vfs/async_opfs/client.dart:1:8: Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html';
        ^
/home/flutter/.pub-cache/hosted/pub.dev/sqlite3-2.4.2/lib/src/wasm/vfs/async_opfs/worker.dart:1:8: Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html';
        ^
* * *

it can be related to the: https://github.com/simolus3/sqlite3.dart/issues/230

please, take a look 
https://dart.dev/interop/js-interop
https://dart.dev/interop/js-interop/package-web

**Comment by simolus3** [comment]
Please don't open obvious duplicates. The newer 2.4.3 version of this package also supports being compiled to WebAssembly already, it's just not feature complete (see the linked issue).
