### ISSUE TITLE
[ QUESTION ] is this package containing db  path helper?

### ISSUE THREAD

**Issue by Krzysztof-Lempicki** [simolus3/sqlite3.dart#243]
## Context

I'm opening my db like this:

```
var db = sqlite3.open('my.db');
```

## Challenge 

When running app on linux everything is fine.
When running in android and new db should be created I got: 

```
SqliteException(14): while opening the database, unable to open database file, unable to open database file (code 14)
```

My assumption is that it is the path problem.
My app can will be deployed on Android and Ios and I'm looking a simple way to handle this issue.

## Question

Does this package contain any class that I can use that will give me correct path depending on platform?

**Comment by simolus3** [comment]
It doesn't, as that would require a Flutter dependency which we can't have here. Use `path_provider` to find a suitable path and then open the database there. Using relative paths will resolve them against the working directory.
