### ISSUE TITLE
Unavailable library `dart:ffi` and missing type errors when trying to run on web

### ISSUE THREAD

**Issue by chrsrns** [simolus3/sqlite3.dart#244]
This [stackexchange post](https://stackoverflow.com/questions/78626240/flutter-drift-for-the-web-unsupported-operation-unsupported-invalid-type-invali) and simolus3/drift#2355 is probably related to this, but I do not know what to do with that info.

Trying to run [this small pet project of mine](https://github.com/chrsrns/habit-tracker-flutter) throws the error below. 

# Steps to Reproduce
- Clone https://github.com/chrsrns/habit-tracker-flutter
- Run `flutter run -d chrome`

# Error output

[output-log.txt](https://github.com/user-attachments/files/15944994/output-log.txt)

<pre>Launching lib/main.dart on Chrome in debug mode...
<font color="#2AA1B3">Warning: In index.html:37: Local variable for &quot;serviceWorkerVersion&quot; is deprecated. Use &quot;{{flutter_service_worker_version}}&quot; template token instead.</font>
<font color="#2AA1B3">Warning: In index.html:46: &quot;FlutterLoader.loadEntrypoint&quot; is deprecated. Use &quot;FlutterLoader.load&quot; instead.</font>
<font color="#C01C28">/home/user/.pub-cache/hosted/pub.dev/sqlite3-2.4.2/lib/src/ffi/api.dart:1:8: Error: Dart library &apos;dart:ffi&apos; is not available on this platform.</font>
<font color="#C01C28">import &apos;dart:ffi&apos;;</font>
<font color="#C01C28">       ^</font>
<font color="#C01C28">Context: The unavailable library &apos;dart:ffi&apos; is imported through these packages:</font>

<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit =&gt; package:sqlite3 =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit =&gt; package:sqlite3 =&gt; package:ffi =&gt; dart:ffi</font>

<font color="#C01C28">Detailed import paths for (some of) the these imports:</font>

<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/open.dart =&gt; package:sqlite3/src/ffi/load_library.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/open.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; package:sqlite3/src/ffi/bindings.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; package:sqlite3/src/ffi/bindings.dart =&gt; package:sqlite3/src/ffi/memory.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; package:sqlite3/src/ffi/bindings.dart =&gt; package:sqlite3/src/ffi/memory.dart =&gt; package:ffi/ffi.dart =&gt;</font>
<font color="#C01C28">    package:ffi/src/allocation.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; package:sqlite3/src/ffi/bindings.dart =&gt; package:sqlite3/src/ffi/memory.dart =&gt; package:ffi/ffi.dart =&gt;</font>
<font color="#C01C28">    package:ffi/src/arena.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; package:sqlite3/src/ffi/bindings.dart =&gt; package:sqlite3/src/ffi/memory.dart =&gt; package:ffi/ffi.dart =&gt;</font>
<font color="#C01C28">    package:ffi/src/utf8.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; package:sqlite3/src/ffi/bindings.dart =&gt; package:sqlite3/src/ffi/memory.dart =&gt; package:ffi/ffi.dart =&gt;</font>
<font color="#C01C28">    package:ffi/src/utf16.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; package:sqlite3/src/ffi/bindings.dart =&gt; package:sqlite3/src/ffi/memory.dart =&gt; package:sqlite3/src/ffi/sqlite3.g.dart</font>
<font color="#C01C28">    =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; package:sqlite3/src/ffi/bindings.dart =&gt; package:sqlite3/src/ffi/sqlite3.g.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; package:sqlite3/src/ffi/memory.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; package:sqlite3/src/ffi/memory.dart =&gt; package:ffi/ffi.dart =&gt; package:ffi/src/allocation.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; package:sqlite3/src/ffi/memory.dart =&gt; package:ffi/ffi.dart =&gt; package:ffi/src/arena.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; package:sqlite3/src/ffi/memory.dart =&gt; package:ffi/ffi.dart =&gt; package:ffi/src/utf8.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; package:sqlite3/src/ffi/memory.dart =&gt; package:ffi/ffi.dart =&gt; package:ffi/src/utf16.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; package:sqlite3/src/ffi/memory.dart =&gt; package:sqlite3/src/ffi/sqlite3.g.dart =&gt; dart:ffi</font>
<font color="#C01C28">    web_entrypoint.dart =&gt; package:cohabit/main.dart =&gt; package:cohabit/landing_screen.dart =&gt; package:cohabit/home_page.dart =&gt; package:cohabit/nav_destinations.dart =&gt; package:cohabit/habit_list_page.dart =&gt;</font>
<font color="#C01C28">    package:sqlite3/sqlite3.dart =&gt; package:sqlite3/src/ffi/api.dart =&gt; package:sqlite3/src/ffi/implementation.dart =&gt; package:sqlite3/src/ffi/sqlite3.g.dart =&gt; dart:ffi</font>

<font color="#C01C28">/home/user/.pub-cache/hosted/pub.dev/sqlite3-2.4.2/lib/open.dart:5:8: Error: Dart library &apos;dart:ffi&apos; is not available on this platform.</font>
<font color="#C01C28">import &apos;dart:ffi&apos;;</font>
<font color="#C01C28">       ^</font>
<font color="#C01C28">/home/user/.pub-cache/hosted/pub.dev/sqlite3-2.4.2/lib/src/ffi/implementation.dart:1:8: Error: Dart library &apos;dart:ffi&apos; is not available on this platform.</font>
<font color="#C01C28">import &apos;dart:ffi&apos;;</font>
<font color="#C01C28">       ^</font>
<font color="#C01C28">/home/user/.pub-cache/hosted/pub.dev/sqlite3-2.4.2/lib/src/ffi/load_library.dart:1:8: Error: Dart library &apos;dart:ffi&apos; is not available on this platform.</font>
<font color="#C01C28">import &apos;dart:ffi&apos;;</font>
<font color="#C01C28">       ^</font>
<font color="#C01C28">/home/user/.pub-cache/hosted/pub.dev/sqlite3-2.4.2/lib/src/ffi/bindings.dart:3:8: Error: Dart library &apos;dart:ffi&apos; is not available on this platform.</font>
<font color="#C01C28">import &apos;dart:ffi&apos;;</font>
<font color="#C01C28">       ^</font>
<font color="#C01C28">/home/user/.pub-cache/hosted/pub.dev/sqlite3-2.4.2/lib/src/ffi/memory.dart:2:8: Error: Dart library &apos;dart:ffi&apos; is not available on this platform.</font>
<font color="#C01C28">import &apos;dart:ffi&apos;;</font>
<font color="#C01C28">       ^</font>
<font color="#C01C28">/home/user/.pub-cache/hosted/pub.dev/sqlite3-2.4.2/lib/src/ffi/sqlite3.g.dart:5:8: Error: Dart library &apos;dart:ffi&apos; is not available on this platform.</font>
<font color="#C01C28">import &apos;dart:ffi&apos; as ffi;</font>
<font color="#C01C28">       ^</font>
<font color="#C01C28">/home/user/.pub-cache/hosted/pub.dev/ffi-2.1.2/lib/src/allocation.dart:5:8: Error: Dart library &apos;dart:ffi&apos; is not available on this platform.</font>
<font color="#C01C28">import &apos;dart:ffi&apos;;</font>
<font color="#C01C28">       ^</font>
<font color="#C01C28">/home/user/.pub-cache/hosted/pub.dev/ffi-2.1.2/lib/src/arena.dart:8:8: Error: Dart library &apos;dart:ffi&apos; is not available on this platform.</font>
<font color="#C01C28">import &apos;dart:ffi&apos;;</font>
<font color="#C01C28">       ^</font>
...
...
...
<font color="#C01C28">/home/user/.pub-cache/hosted/pub.dev/ffi-2.1.2/lib/src/utf16.dart:95:11: Error: &apos;Pointer&apos; isn&apos;t a type.</font>
<font color="#C01C28">    final Pointer&lt;Uint16&gt; result = allocator&lt;Uint16&gt;(units.length + 1);</font>
<font color="#C01C28">          ^^^^^^^</font>
<font color="#C01C28">/home/user/.pub-cache/hosted/pub.dev/ffi-2.1.2/lib/src/utf16.dart:95:46: Error: &apos;Uint16&apos; isn&apos;t a type.</font>
<font color="#C01C28">    final Pointer&lt;Uint16&gt; result = allocator&lt;Uint16&gt;(units.length + 1);</font>
<font color="#C01C28">                                             ^^^^^^</font>
<font color="#C01C28">Unhandled exception:</font>
<font color="#C01C28">Unsupported operation: Unsupported invalid type InvalidType(&lt;invalid&gt;) (InvalidType). Encountered while compiling file:///home/user/.pub-cache/hosted/pub.dev/sqlite3-2.4.2/lib/src/ffi/implementation.dart, which contains the type:</font>
<font color="#C01C28">FunctionType(FfiSqlite3 Function(&lt;invalid&gt;)).</font>
<font color="#C01C28">#0      ProgramCompiler._typeCompilationError (package:dev_compiler/src/kernel/compiler.dart:3236)</font>
<font color="#C01C28">#1      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:3197)</font>
<font color="#C01C28">#2      ProgramCompiler._emitClassSignature (package:dev_compiler/src/kernel/compiler.dart:1570)</font>
<font color="#C01C28">#3      ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:962)</font>
<font color="#C01C28">#4      ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:819)</font>
<font color="#C01C28">#5      List.forEach (dart:core-patch/growable_array.dart:416)</font>
<font color="#C01C28">#6      ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:757)</font>
<font color="#C01C28">#7      List.forEach (dart:core-patch/growable_array.dart:416)</font>
<font color="#C01C28">#8      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:486)</font>
<font color="#C01C28">#9      IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:223)</font>
<font color="#C01C28">#10     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:801)</font>
<font color="#C01C28">&lt;asynchronous suspension&gt;</font>
<font color="#C01C28">#11     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:661)</font>
<font color="#C01C28">&lt;asynchronous suspension&gt;</font>
<font color="#C01C28">#12     listenAndCompile.&lt;anonymous closure&gt; (package:frontend_server/frontend_server.dart:1311)</font>
<font color="#C01C28">&lt;asynchronous suspension&gt;</font>
<font color="#C01C28">the Dart compiler exited unexpectedly.</font>
Waiting for connection from debug service on Chrome...             12.9s
<font color="#C01C28">Failed to compile application.</font></pre>

**Comment by simolus3** [comment]
The core `package:sqlite3/sqlite3.dart` import doesn't work on the web, and never will as it depends on `dart:ffi`. Getting sqlite3 to run on the web is pretty complex due to varying browser support, and none of that is implemented in the core `sqlite3` package. I strongly suggest using a wrapper like `drift` or `sqflite` (with `sqflite_common_ffi_web` for the web) which takes care of this for you.

You can work around this problem by replacing most of your `package:sqlite3/sqlite3.dart` imports with `package:sqlite3/common.dart`, `Database` with `CommonDatabase` and so on. Then the only remaining challenge is how you open sqlite3 databases on the web, for which [this section of the readme](https://pub.dev/packages/sqlite3#wasm-web-support) provides some ideas.

**Comment by chrsrns** [comment]
I see. I get it now. It seems I accidentally imported `package:sqlite3/sqlite3.dart` somewhere in the code. Sorry for the noise and thank you for the time.

**Comment by isaanyoha** [comment]
I get same isseue.

So going with your suggestion by using common.dart, i want to use same code for both web and other platforms. How do I open database for non-web while calling only 'package:sqlite3/common.dart' without calling 'package:sqlite3/sqlite3.dart'.


the error tells me to import sqlite3.dart

 
<img width="851" alt="Image" src="https://github.com/user-attachments/assets/cc2b92c3-615d-415c-a442-ded57abdd28b" />

**Comment by simolus3** [comment]
Hi, you can use [conditional imports](https://dart.dev/tools/pub/create-packages#conditionally-importing-and-exporting-library-files) to make sure that the native parts are not included for web builds (and also to avoid the web parts being included for native builds). You don't need to refactor your entire database code for this, a few steps are enough:

Create the files `open_database_stub.dart`, `open_database_native.dart`, `open_database_web.dart`. They should have the following contents:

```dart
// open_database_stub.dart
import 'package:sqlite3/common.dart';

Future<CommonDatabase> openDatabase() async {
  throw UnsupportedError('Unknown platform');
}
```

```dart
// open_database_native.dart
import 'package:sqlite3/common.dart';
import 'package:sqlite3/sqlite3.dart';

Future<CommonDatabase> openDatabase() async {
  final path = await getPath();
  return sqlite3.open(path)..execute('pragma journal_mode = WAL;');
}
```

```dart
// open_database_web.dart
import 'package:sqlite3/common.dart';
import 'package:sqlite3/wasm.dart';

Future<CommonSqlite3> openDatabase() async {
  final sqlite =  await WasmDatabase.loadFromUrl(Uri.parse('sqlite3.wasm'));
  final fs = await IndexedDbFileSystem.open(name: 'app.db');
  sqlite.registerVirtualFileSystem(fs, makeDefault: true);
  return sqlite.open('/app.db');
}
```

In your main database file, use

```dart
import 'open_database_stub.dart'
  if (dart.library.native) 'open_database_native.dart'
  if (dart.library.js_interop) 'open_database_web.dart';
```

With that, you can just use `final CommonDatabase database = await openDatabase();` and avoid the compilation errors.

**Comment by isaanyoha** [comment]
Thanks for this quick reply! I appreciate. Let me try what you said and revert back.

**Comment by isaanyoha** [comment]
It worked!!

I can now run my app with sqlite on the web! So, why the rumor that sqlite can't run on the web?
Thanks @simolus3 for this amazing package.

One more little thing...

For some reason, the if for the import does not work properly as stub gets used all the time I try (even for web & native)
. And so, I just use one for the actually platform and comment the conditions

How do i fix this, please...

<img width="911" alt="Image" src="https://github.com/user-attachments/assets/382e2261-7dfd-4fe0-906f-8ff9f3c9c3c8" />

**Comment by simolus3** [comment]
`dart.library.native` should be `dart.library.io`, my bad. I'm surprised `dart.library.js_interop` doesn't work though, which Dart/Flutter version are you on?

**Comment by isaanyoha** [comment]
Oh,

Flutter 3.27.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c519ee916e (8 days ago) • 2025-01-21 10:32:23 -0800
Engine • revision e672b006cb
Tools • Dart 3.6.1 • DevTools 2.40.2

**Comment by isaanyoha** [comment]
Ok, fixed now.

I downgraded my flutter version

**Comment by simolus3** [comment]
That should not be necessary. I made some typos in the web snippet, but the conditional imports as I've posted them work for me in Flutter 3.27.3 (tested running a new app on Linux and Chrome).
