### ISSUE TITLE
createFunction Async Support

### ISSUE THREAD

**Issue by rodydavis** [simolus3/sqlite3.dart#249]
Is it possible to create a function that is async?

For example, this works fine:

```dart
import 'package:drift/wasm.dart';
import 'package:sqlite3/common.dart';

void setupDatabase(CommonDatabase database) {
  database.createFunction(
    functionName: 'my_function',
    function: (args) {
      return args.length;
    },
  );
}

void main() {
  WasmDatabase.workerMainForOpen(
    setupAllDatabases: setupDatabase,
  );
}

```

But throws and error when made async:

```dart
import 'package:drift/wasm.dart';
import 'package:sqlite3/common.dart';

void setupDatabase(CommonDatabase database) {
  database.createFunction(
    functionName: 'my_function',
    function: (args) async {
      await Future.delayed(const Duration(seconds: 2));
      return args.length;
    },
  );
}

void main() {
  WasmDatabase.workerMainForOpen(
    setupAllDatabases: setupDatabase,
  );
}

```

Use case would be embedding functions for vector support like the following:
- https://github.com/asg017/sqlite-rembed
- https://github.com/asg017/sqlite-lembed

**Comment by simolus3** [comment]
Unfortunately we won't be able to support asynchronous functions. This whole library is synchronous, so there's no good way to actually await the future. And then sqlite3, being a C library, also expects user-defined functions to return a value synchronously (we could return a user-defined object as a handle, but then you wouldn't be able to inspect that value in SQL at all).

If you look at sqlite-rembed, you'll see that it also uses synchronous functions only.

**Comment by rodydavis** [comment]
Sounds good! Figured that was the case but thought I would ask.
