### ISSUE TITLE
sqlite3_web: Flushing IndexedDbFileSystem

### ISSUE THREAD

**Issue by rkistner** [simolus3/sqlite3.dart#259]
`IndexedDbFileSystem` exposes a `flush()` method to wait until data is flushed to persistent storage. Is there a way to access this with the `sqlite3_web` package?

In my testing after the performance improvements in #258, I can loose up to half the recent changes to the database when I refresh the page, while busy with a high throughput of insert statements. Either having an option to flush automatically after each statement/transaction, or the ability to manually call flush from the DatabaseController would work for me.

**Comment by simolus3** [comment]
Version `0.2.0` of `sqlite3_web` has a method to explicitly flush the file system via `Database.filesystem.flush()`.
