### ISSUE TITLE
Null-safety for sqlitecipher_flutter_libs

### ISSUE THREAD

**Issue by justacid** [simolus3/sqlite3.dart#26]
Hi there!

I'm using moor with `sqlitecipher_flutter_libs` as documented [here](https://moor.simonbinder.eu/docs/other-engines/encryption/) on the bottom of the page. I've noticed that `sqlite3_flutter_libs` has a published version with null-safety enabled, but the `sqlitecipher_flutter_libs` variant has not yet enabled null-safety:

https://github.com/simolus3/sqlite3.dart/blob/7a226a08993ac3374fb7ddb4fe62112d941dea61/sqlcipher_flutter_libs/pubspec.yaml#L8

Is this an oversight, or do you recommend the other approach described [here](https://moor.simonbinder.eu/docs/other-engines/encryption/) to setting up sqlcipher with moor? Does this even work anymore (I could not find the branch extras/encryption on the moor repo)?

**Comment by simolus3** [comment]
> I could not find the branch extras/encryption on the moor repo

It's a path, not a git ref :) The `encrypted_moor` package is still part of the moor repository.

Either way, I've "migrated" that package to null safety in f01c09933b9d0cc0f4098408f855ff00769a5757. But note that in general the packages that you don't import directly (like `sqlcipher_flutter_libs`, `moo_generator`, `build_runner` etc.) are not blocking a migration of your app.

**Comment by justacid** [comment]
That was fast! Thank you very much! 😄 

> It's a path, not a git ref :) The encrypted_moor package is still part of the moor repository.

D'oh! Of course! Don't know why I didn't notice. 🤦🏻 

> But note that in general the packages that you don't import directly (like sqlcipher_flutter_libs, moo_generator, build_runner etc.) are not blocking a migration of your app.

Thanks for pointing that out to me! I was only aware that the dev_dependencies are not blocking a migration. 👍🏻
