### ISSUE TITLE
Insert multiple rows at once

### ISSUE THREAD

**Issue by tp** [simolus3/sqlite3.dart#260]
Is there any way to insert many (a variable number in my case) rows at once with something like `execute`?

I have only found these hard-coded values in the test cases, but not any facilities to do this with a list of `parameters`:

https://github.com/simolus3/sqlite3.dart/blob/d2c2dcf4659dffe197cea644ee80a4e7d82e31ed/sqlite3/test/database_test.dart#L326

So far I am looping over the rows to insert, but I wonder how much fast it could be it they are inserted all in one query :)

I have seen [this comment](https://github.com/simolus3/sqlite3.dart/issues/155#issuecomment-1511299600), but in my testing for the initial load if still takes >10ms to insert 3000 rows (across 2 tables), which is just a bit too much IMHO. But I would like to get this sped up so as to not be a blocker, as in all subsequent reads/writes in that project the synchronous nature of this library is much preferred.

**Comment by simolus3** [comment]
Using prepared statements multiple times is the fastest way to do bulk inserts that SQLite has to offer. Are you wrapping the insert loop in a transaction? If not, each individual call starts a short-lived transaction that needs to be written to disk before we can continue. Putting them in a transaction usually speeds things up significantly.

If things are still too slow with a transaction, using a temporary isolate for that (you can't share database connections across isolates directly, but opening the same database files on different isolates is safe) is the only alternative that comes to mind.

**Comment by simolus3** [comment]
> continual context switches between Dart & SQLite (3000 INSERT operations, instead of just one).

The overhead of `dart:ffi` isn't that bad and SQLite runs in the same process, so there's no context switch.

> Just to be sure, technically this could be something that the library can support and would likely speed up my use-case, it's just not something you're currently interested in, right?

I'm not sure what "this" is here - SQLite does not offer a function to run multiple statements with parameters in a single call. The current approach you're using for batch inserts is likely already the fastest possible. 
(there's certainly potential to profile and optimize this to make this a little bit faster, but it's there's no magic way to make this substantially faster)
