### ISSUE TITLE
Flutter Query method parameters have to be non-nullable.

### ISSUE THREAD

**Issue by wgmsky** [simolus3/sqlite3.dart#27]
I tried to use the build runner generating my database class in AS But the terminal prompts this error after the command 
'Query method parameters have to be non-nullable. Define uid as non-nullable.
If you want to assert null, change your query to use the `IS NULL`/`IS NOT NULL` operator without passing a nullable parameter.'

**Comment by simolus3** [comment]
Hi, and thanks for opening an issue. Judging from the error, it looks like this error comes from floor and is unrelated to this package.

I think you might be able to check https://github.com/vitusortner/floor/issues/507 for more information.

**Comment by wgmsky** [comment]
> Hi, and thanks for opening an issue. Judging from the error, it looks like it comes from floor and is unrelated to this package.
> 
> I think you might be able to check [vitusortner/floor#507](https://github.com/vitusortner/floor/issues/507) for more information.

Thank you so much for answering me question ! best wishes to you !
