### ISSUE TITLE
[Question] How to delete web databases

### ISSUE THREAD

**Issue by rodydavis** [simolus3/sqlite3.dart#271]
There is an API to add the initial bytes for a web database, but what is the current way to delete one?

If I am using SQLite as a file format I will want to override the bytes in place even if it exists or delete one (like when a user logs out).

**Comment by simolus3** [comment]
For IndexedDb, you can use `IndexedDbFileSystem.deleteDatabase` to delete the entire backing of the file system. I'll also add a similar method to the OPFS file system.

**Comment by rodydavis** [comment]
Yeah I was wondering about OPFS since I delete with indexeddb the way you mentioned!
