### ISSUE TITLE
android 6.1 for sqlcipher_flutter_libs

### ISSUE THREAD

**Issue by Ali1Ammar** [simolus3/sqlite3.dart#29]
i see there is error with dynamic link in old phone and some 6.1 device
there is `applyWorkaroundToOpenSqlite3OnOldAndroidVersions` for sqlite3_flutter_libs but not for sqlcipher_flutter_libs
also when we override like this as describe in moor docs  will break old device  because we need to use full path with id on old device 
```dart
  open.overrideFor(
      OperatingSystem.android, () => DynamicLibrary.open('libsqlcipher.so'));
```

i suggest to add this to sqlcipher_flutter_libs : 

1- applyWorkaroundToOpenSqlite3OnOldAndroidVersions 

2- provide openCipherOnAndroid function that do this 
```dart
DynamicLibrary openCipherOnAndroid() {
  try {
    return DynamicLibrary.open('libsqlcipher.so');
  } catch (_) {
    // On some (especially old) Android devices, we somehow can't dlopen
    // libraries shipped with the apk. We need to find the full path of the
    // library (/data/data/<id>/lib/libsqlcipher.so) and open that one.
    // For details, see https://github.com/simolus3/moor/issues/420
    final appIdAsBytes = File('/proc/self/cmdline').readAsBytesSync();

    // app id ends with the first \0 character in here.
    final endOfAppId = max(appIdAsBytes.indexOf(0), 0);
    final appId = String.fromCharCodes(appIdAsBytes.sublist(0, endOfAppId));

    return DynamicLibrary.open('/data/data/$appId/lib/libsqlcipher.so');
  }
}
```
then programmer could do 
```dart
  open.overrideFor(
      OperatingSystem.android, openCipherOnAndroid);
```

i am happy to make pull request if this way ok .

**Comment by simolus3** [comment]
A pull request would be great, thanks :+1:
