### ISSUE TITLE
sqlcipher_flutter_libs does not compile

### ISSUE THREAD

**Issue by MobiliteDev** [simolus3/sqlite3.dart#32]
I'm trying to compile sqlite3.dart package with Flutter 2.0.3 installed.

I have errors in sqlcipher_flutter_libs.dart
![image](https://user-images.githubusercontent.com/54275508/117273425-69c9f700-ae5c-11eb-87ad-070b2d34946a.png)

If I add Flutter dependency in the pubspec.yaml, it is working
![image](https://user-images.githubusercontent.com/54275508/117273584-8ebe6a00-ae5c-11eb-8230-704a1a06b549.png)

Is it normal ?

**Comment by simolus3** [comment]
Sorry, I should have caught that myself. This is fixed now, thanks for the report.
