### ISSUE TITLE
[Proposal] Rename Row class

### ISSUE THREAD

**Issue by MobiliteDev** [simolus3/sqlite3.dart#34]
If you use sqlite3 inside flutter App, you could have conflicts name between Flutter.Row and Sqlite3.Row.
![image](https://user-images.githubusercontent.com/54275508/118959403-956fd580-b962-11eb-9786-6ec42e6c8ad6.png)

Do you think it could be a good idea to rename you Row class into SqlRow or RowSql for example ?

**Comment by simolus3** [comment]
In general my take is that users should use hide/show directives to resolve this:

```dart
import 'package:flutter/material.dart' hide Row;
```

`Row` is a good class name for a row, so I don't think renaming it would be worth it.
