### ISSUE TITLE
update .gitignore

### ISSUE THREAD

**Issue by MobiliteDev** [simolus3/sqlite3.dart#39]
Hi,

Could be possible for you to update some part of your main .gitignore this lines please in order to follow the [Flutter .gitignore](https://github.com/flutter/flutter/blob/master/.gitignore) like this below ?

```code
# Flutter/Dart/Pub related
**/doc/api/
.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
**/generated_plugin_registrant.dart
.packages
.pub-cache/
.pub/
build/
flutter_*.png
linked_*.ds
unlinked.ds
unlinked_spec.ds
```

Or more if you want, because in my case '.flutter-plugins-dependencies' is automatically generated and doesn't need to be tracked.

**Comment by simolus3** [comment]
I already had most of these in my gitignore, I've added the rest as well now.

**Comment by MobiliteDev** [comment]
yes, perfect thank you, but I think you have forgotten `.flutter-plugins-dependencies`.
Tell me if you prefer a PR for this kind of change or if an issue is enough.

**Comment by simolus3** [comment]
Feel free to open a PR, thanks :)
