### ISSUE TITLE
Add constants

### ISSUE THREAD

**Issue by MobiliteDev** [simolus3/sqlite3.dart#41]
I found this example on the official dart repo, an FFI implementation of SQLite.
https://github.com/dart-lang/sdk/tree/master/samples/ffi/sqlite

In this example, the class `contants.dart` [defines](https://github.com/dart-lang/sdk/blob/master/samples/ffi/sqlite/lib/src/bindings/constants.dart) more SQLite constants knew [here](https://www.sqlite.org/rescode.html#done).

What do you think of this approach ? 
Do you think it could be a good idea to update sqlite3 to looks like to it ?

If yes, I could help with a PR.

**Comment by simolus3** [comment]
The constants defined in this library are all internal and not part of any public api.

I think we can add error codes to the public api since they're generally helpful to help distinguish between exceptions. A PR would be appreciated, thanks!
