### ISSUE TITLE
CocoaPods could not find compatible versions for pod "SQLCipher" for platform :ios, '11.0'

### ISSUE THREAD

**Issue by devaronius** [simolus3/sqlite3.dart#43]
While updating the app to work with flutter 2.2.1 I run into the problem where cocoa pods can't find sqflite_sqlcipher when the pod file platform is set to 11.

[!] CocoaPods could not find compatible versions for pod "SQLCipher":
  In Podfile:
    sqflite_sqlcipher (from `.symlinks/plugins/sqflite_sqlcipher/ios`) was resolved to 0.0.1, which depends on
      SQLCipher (= 4.4.2)

    sqlcipher_flutter_libs (from `.symlinks/plugins/sqlcipher_flutter_libs/ios`) was resolved to 0.0.1, which depends on
      SQLCipher (~> 4.4.3)
      

on platform:ios, '10' this still works, but the latest versions of firebase require version 11 and higher.

the defaults ways of:
- removing podfile.lock 
- rm -rf ~/.cocoapods/repos
- pod install --repo-update
- flutter clean

doesn't work.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.2.1 20D74 darwin-x64, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

**Comment by simolus3** [comment]
Is that the full error message? I don't see where the incompatibility would come from, as both `sqlcipher_flutter_libs` and `SQLCipher` use `platform = :ios, '8.0'` in their podspecs. I don't see anything that would prevent a newer ios target.

**Comment by devaronius** [comment]
the full error code is:

Running pod install...
CocoaPods' output:
↳
    pharmacy: Using Firebase SDK version '8.0.0' defined in 'firebase_core for FirebaseFirestore framework'
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Pre-downloading: `FirebaseFirestore` from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `8.0.0`
      > Copying FirebaseFirestore from `/Users/stefan/Library/Caches/CocoaPods/Pods/External/FirebaseFirestore/800da38ffb8d4cc2520c3dc091581139` to `Pods/FirebaseFirestore`
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `app_tracking_transparency` from `.symlinks/plugins/app_tracking_transparency/ios`
    -> Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
    -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
    cloud_firestore: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
    -> Fetching podspec for `connectivity_plus` from `.symlinks/plugins/connectivity_plus/ios`
    -> Fetching podspec for `firebase_analytics` from `.symlinks/plugins/firebase_analytics/ios`
    firebase_analytics: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    firebase_auth: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    firebase_core: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_crashlytics` from `.symlinks/plugins/firebase_crashlytics/ios`
    firebase_crashlytics: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_in_app_messaging` from `.symlinks/plugins/firebase_in_app_messaging/ios`
    firebase_in_app_messaging: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_performance` from `.symlinks/plugins/firebase_performance/ios`
    firebase_performance: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_remote_config` from `.symlinks/plugins/firebase_remote_config/ios`
    firebase_remote_config: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
    -> Fetching podspec for `flutter_local_notifications` from `.symlinks/plugins/flutter_local_notifications/ios`
    -> Fetching podspec for `flutter_native_timezone` from `.symlinks/plugins/flutter_native_timezone/ios`
    -> Fetching podspec for `flutter_secure_storage` from `.symlinks/plugins/flutter_secure_storage/ios`
    -> Fetching podspec for `flutter_web_browser` from `.symlinks/plugins/flutter_web_browser/ios`
    -> Fetching podspec for `google_ml_vision` from `.symlinks/plugins/google_ml_vision/ios`
    -> Fetching podspec for `local_auth` from `.symlinks/plugins/local_auth/ios`
    -> Fetching podspec for `notificare_push_lib` from `.symlinks/plugins/notificare_push_lib/ios`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `sms_autofill` from `.symlinks/plugins/sms_autofill/ios`
    -> Fetching podspec for `sqflite_sqlcipher` from `.symlinks/plugins/sqflite_sqlcipher/ios`
    -> Fetching podspec for `sqlcipher_flutter_libs` from `.symlinks/plugins/sqlcipher_flutter_libs/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_0_3_5.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.1.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.0.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_c_7_9.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/7/9/Reachability/3.2/Reachability.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.0.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.0.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.0.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.0.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.0.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_b_e_b.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/b/e/b/GoogleMLKit/2.1.0/GoogleMLKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/b/e/b/GoogleMLKit/2.1.0/GoogleMLKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/b/e/b/GoogleMLKit/2.1.0/GoogleMLKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/b/e/b/GoogleMLKit/2.1.0/GoogleMLKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/b/e/b/GoogleMLKit/2.1.0/GoogleMLKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_f_9_6.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/f/9/6/notificare-push-lib/2.6.0/notificare-push-lib.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_f_4_e.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_1_2_7.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/2/7/SQLCipher/4.4.3/SQLCipher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.0.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.0.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/f/9/6/notificare-push-lib/2.5.2/notificare-push-lib.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/b/e/b/GoogleMLKit/2.1.0/GoogleMLKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_a_f_4.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/a/f/4/MLKitFaceDetection/1.2.0/MLKitFaceDetection.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/a/f/4/MLKitFaceDetection/1.2.0/MLKitFaceDetection.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_c_c_6.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/c/6/MLKitCommon/2.1.0/MLKitCommon.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_8_1_e.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/8/1/e/MLKitVision/1.2.0/MLKitVision.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/8/1/e/MLKitVision/1.2.0/MLKitVision.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_c_e_3.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.5.0/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.0/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.1/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.2/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.3/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.4/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.5/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.6/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.7/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.8/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.9/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.10/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.11/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.12/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.13/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.14/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.15/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.2.0/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.2.1/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.2.2/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.3.0/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.3.1/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.4.0/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.5.0/GTMSessionFetcher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_7_4_b.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.3.1/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.1.0/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.1.1/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.1.2/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.1.3/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.1.4/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.2.0/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.2.1/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.2.2/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.3.0/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.3.1/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.1.0/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.1.1/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.1.2/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.1.3/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.1.4/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.2.0/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.2.1/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.2.2/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.3.0/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.3.1/GoogleToolboxForMac.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_e_c_d.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/c/d/Protobuf/4.0.0-rc1/Protobuf.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/8.0.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_e_2_1.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/2/1/FirebaseAnalytics/8.1.0/FirebaseAnalytics.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/2/1/FirebaseAnalytics/8.0.0/FirebaseAnalytics.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_8_b_d.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/8/b/d/FirebaseCore/8.1.0/FirebaseCore.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_2_f_7.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/2/f/7/FirebaseInstallations/8.1.0/FirebaseInstallations.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_0_8_4.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.4.1/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.4.0/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.4.1/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.4.0/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.4.1/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.4.0/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.4.1/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.4.0/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/8/4/GoogleUtilities/7.4.1/GoogleUtilities.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_6_1_e.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/6/1/e/nanopb/2.30908.0/nanopb.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/2/1/FirebaseAnalytics/8.0.0/FirebaseAnalytics.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/2/1/FirebaseAnalytics/8.0.0/FirebaseAnalytics.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_e_3_b.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/3/b/GoogleAppMeasurement/8.1.0/GoogleAppMeasurement.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/3/b/GoogleAppMeasurement/8.0.0/GoogleAppMeasurement.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/3/b/GoogleAppMeasurement/8.0.0/GoogleAppMeasurement.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/2/7/SQLCipher/4.4.2/SQLCipher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/2/7/SQLCipher/4.4.2/SQLCipher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/2/7/SQLCipher/4.4.3/SQLCipher.podspec.json exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "SQLCipher":
      In Podfile:
        sqflite_sqlcipher (from `.symlinks/plugins/sqflite_sqlcipher/ios`) was resolved to 0.0.1, which depends on
          SQLCipher (= 4.4.2)

        sqlcipher_flutter_libs (from `.symlinks/plugins/sqlcipher_flutter_libs/ios`) was resolved to 0.0.1, which depends on
          SQLCipher (~> 4.4.3)

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:702:in `attempt_to_filter_existing_spec'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:673:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone 12 Pro.

with the following podfile

`# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

require 'yaml'

pubspec = YAML.load_file(File.join('..', 'pubspec.yaml'))

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  if defined?($FirebaseSDKVersion)
    Pod::UI.puts "#{pubspec['name']}: Using user specified Firebase SDK version for FirebaseFirestore framework: '#{$FirebaseSDKVersion}'"
    firebase_sdk_version = $FirebaseSDKVersion
  else
    firebase_core_script = File.expand_path(File.join('..', '.symlinks', 'plugins', 'firebase_core/ios/firebase_sdk_version.rb'), __FILE__)
    if File.exist?(firebase_core_script)
      require firebase_core_script
      firebase_sdk_version = firebase_sdk_version!
      Pod::UI.puts "#{pubspec['name']}: Using Firebase SDK version '#{firebase_sdk_version}' defined in 'firebase_core for FirebaseFirestore framework'"
    else
      raise "Error - unable to locate `#{firebase_core_script}` script in firebase_core, and no FirebaseSDKVersion specified"
    end
  end

  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => "#{firebase_sdk_version}"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |bc|
        # You can remove unused permissions here
              # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/permission_handler/ios/Classes/PermissionHandlerEnums.h
              # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
              bc.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
                '$(inherited)',

                ## dart: PermissionGroup.calendar
                'PERMISSION_EVENTS=0',

                ## dart: PermissionGroup.contacts
                'PERMISSION_CONTACTS=0',

                ## dart: PermissionGroup.microphone
                'PERMISSION_MICROPHONE=0',

                ## dart: PermissionGroup.speech
                'PERMISSION_SPEECH_RECOGNIZER=0',

                ## dart: PermissionGroup.photos
                'PERMISSION_PHOTOS=0',

                ## dart: PermissionGroup.mediaLibrary
                'PERMISSION_MEDIA_LIBRARY=0',

                ## dart: PermissionGroup.sensors
                'PERMISSION_SENSORS=0'
              ]

        flutter_additional_ios_build_settings(target)
    end
  end
end
`

**Comment by simolus3** [comment]
Ah, now I understand what's going on here. `sqlcipher_flutter_libs` wants a `SQLCipher` version newer than the one `sqflite_sqlcipher` depends on.

Do you have a dependency on both packages? You can probably drop `sqlcipher_flutter_libs` if you're using the `sqflite_sqlcipher` package somewhere in your code.

**Comment by devaronius** [comment]
thanks, that solved the problem. 

I did have the `sqlcipher_flutter_libs`  as an override in my pubspec
and after removing it. the build succeeded again.

```
#  sqlcipher_flutter_libs:
#    git:
#      url: https://github.com/simolus3/sqlite3.dart.git
#      path: sqlcipher_flutter_libs
```

**Comment by devaronius** [comment]
I closed the ticket too soon. this resolved the podfile issue but created another where I'm missing the 
`await applyWorkaroundToOpenSqlCipherOnOldAndroidVersions();`

workaround function.

**Comment by simolus3** [comment]
Are you using the `sqlite3` package or `moor/ffi` to access the database? If you don't, you don't need the override either as `sqflite_sqlcipher` is not affected by that problem.

Otherwise, use the `sqlcipher_flutter_libs` package (btw, it's on pub now) and remove the dependency on `sqflite_sqlcipher`.

**Comment by devaronius** [comment]
i'm using `moor/ffi `at the moment for this

**Comment by simolus3** [comment]
Perfect, in that case you can just depend on the latest `sqlcipher_flutter_libs` from pub and remove the `sqflite_sqlcipher` dependency.
