### ISSUE TITLE
run multiple [prepared] statements

### ISSUE THREAD

**Issue by pabiagioli** [simolus3/sqlite3.dart#44]
Hi, I wanted to ask if this library supports running multiple statements and/or multiple prepared statements.
This would allow devs to make custom SQL scripts or maybe make a lookup table from a file with predefined `template` queries

**Comment by simolus3** [comment]
Do you want to prepare multiple sql statements from a single string? If you just want to execute them without parameters you could use `execute`, which supports multiple statements.

**Comment by pabiagioli** [comment]
closing this issue, as it was a question really, and it's been answered. 
if you ever consider making the library able to process a batch of statements with a batch of named parameters, you can reopen this issue.
Thanks!
