### ISSUE TITLE
Sqlcipher not working on iOS when using google_mobile_ads package

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/sqlite3.dart#47]
So this is more as a note to people that may encounter this issue in the future than a question 😅

When using `sqlcipher_flutter_libs` and `google_mobile_ads` (official Admob support for Flutter) at the same time, the Sqlcipher native library wasn't being picked up by the Dart FFI. In fact, `PRAGMA cipher_version` wasn't returning any results.

The problem is that the iOS pod that `google_mobile_ads` uses, links with sqlite3 under the hood, which in return makes the Dart FFI load a normal Sqlite library instead of Sqlcipher.

To **fix it**, you can do the following: XCode -> Project -> Other Linker Flags -> Put "-framework SQLCipher" inside, without the quotes.

More context on the topic:
https://discuss.zetetic.net/t/cannot-open-encrypted-database-with-sqlcipher-4/3654/4 https://discuss.zetetic.net/t/encrypted-db-in-swift-ios-via-fmdb-can-not-open-in-sql-db-browser/4813

Hope this saves a good headache to someone else 😄

**Comment by davidmartos96** [comment]
@simolus3 Do you think it would be worth including the framework step as a general installation instruction for iOS? I don't see any harm telling the build to link with the SQLCipher framework if that is what is going to be used everywhere.

**Comment by simolus3** [comment]
Thanks for the pointers! I've added a warning to the readme in 6dec85f6906b9af43e43705aa87ae416bf8b422a.

**Comment by davidmartos96** [comment]
@simolus3  Just saw the update on the docs, thanks! I guess that to see them in pub.dev a new bump is needed, maybe `0.5.0+1`

**Comment by KiddoV** [comment]
I am still getting the error when using with `google_mobile_ads`.

I already added the `-framework "SQLCipher"` (with or without the quotes)

<img width="974" height="567" alt="Image" src="https://github.com/user-attachments/assets/4a2e7bd6-e7c9-4050-8dce-cc27651b5d45" />

I tried remove all dependencies from `google_mobile_ads`, it works, but add the `google_mobile_ads` back, it don't work again.

Any idea how to fix the issue?
