### ISSUE TITLE
support sqlite3_enable_shared_cache

### ISSUE THREAD

**Issue by SteveAlexander** [simolus3/sqlite3.dart#48]
In recent sqlite versions, there's a per-process shared cache that works across multiple connections. This may be useful in cases where you want to have several processes writing to the same database.

To enable it requires using the api documented here: https://www.sqlite.org/sharedcache.html

There's a global setting:

```
int sqlite3_enable_shared_cache(int);
```

There's also flags to pass to `open`:

> Individual database connections created using sqlite3_open_v2() can choose to participate or not participate in shared cache mode by using the SQLITE_OPEN_SHAREDCACHE or SQLITE_OPEN_PRIVATECACHE flags the third parameter. The use of either of these flags overrides the global shared cache mode setting established by sqlite3_enable_shared_cache(). 

Any thoughts on supporting this?

**Comment by simolus3** [comment]
It looks like you can already do this, I think this should work: `sqlite3.open('file://<path>?cache=shared', uri: true)`. I'm not sure if it makes sense to expose the additional APIs in Dart as well.

**Comment by SteveAlexander** [comment]
oh, great — so, looking at using this with Moor, I guess that's possible by opening with `sqlite3.open` as above, then passing the result to `VmDatabase.opened`

**Comment by simolus3** [comment]
Exactly, that should work. Please let me know if it doesn't or if you're running into other issues :)
