### ISSUE TITLE
FTS Support

### ISSUE THREAD

**Issue by NiranjanShah** [simolus3/sqlite3.dart#5]
Will this library support FTS ? and can a better example be provided with physical database (not in-memory) db ?

**Comment by simolus3** [comment]
> Will this library support FTS?

When using `sqlite3_flutter_libs`, this library should support fts5 on both iOS and Android.

> better example be provided with physical database (not in-memory) db

The example does not aim to demonstrate every method in this library, it should just show the basic concepts. If you want a physical database, use `sqlite3.open(yourFilePath)`. I've added a comment to the example for this.
In general, if you want to see everything this library has to offer, you'll have to check its [api reference](https://pub.dev/documentation/sqlite3/latest/).
