### ISSUE TITLE
Invoking custom functions crashes on mac

### ISSUE THREAD

**Issue by simolus3** [simolus3/sqlite3.dart#6]

**Comment by mindreframer** [comment]
Is this still the case? I would like to use custom functions on MacOS and in my tests it seems to be working OK... (Recent Mac M1 + Monterey OS). I'm asking to make sure what Mac / OS versions this would concern. 

Could we make a repo with Github Actions CI running across different Mac OS versions? There seems to be  10, 11, 12 VMs available - https://github.com/actions/virtual-environments/tree/main/images/macos. 
With the recent stable support for Flutter on desktops  this issue (if still happening) might become more relevant. 

If there are some actionable steps, I could provide some support in CI setup or creating reproducible crashes for closer inspection. 

Cheers, 
Roman

**Comment by simolus3** [comment]
From my understanding, this has never been a problem when running with Flutter and `sqlite3_flutter_libs`. The crash only occurred when using custom functions with the sqlite3 dylib that comes with macOS.

My best guess at the time was that this is some overly sensitive security thing (e.g. a system library not being able to invoke user code and sqlite3's custom functions not being in the allowlist??). But I'm not experienced enough with macOS to say for sure.

Either way, it also seems to work on macOS 12. Since this is not going to be relevant for most users _and_ it seems to work on macOS now (45a9fe66327d521078be626e2afcdb9da2d8d059), I'll close this as fixed.

I can run an CI pipeline across different macOS versions to see if this still happens with the latest version of the library on older macOS versions if you're interested in that. But if you're using `sqlite3_flutter_libs`, I don't think you'd run into this.

**Comment by mindreframer** [comment]
@simolus3 Thanks for the quick response! Glad to head that this is not happening with Flutter on macOS and that we might get the pipeline running with different macOS versions. 

If you want to, I could look into configuring the CI. Should I create a separate issue for this?

**Comment by simolus3** [comment]
> If you want to, I could look into configuring the CI. Should I create a separate issue for this?

I've started a single run across all macOS versions supported by GitHub in https://github.com/simolus3/sqlite3.dart/actions/runs/2514598470. Judging by that, user-defined functions now seem to work on all macOS versions. Perhaps it was a change in the Dart SDK or some inadvertent change to this library that fixed the problem.

I'll setup some better caching and then enable testing across OS versions going forward.
