### ISSUE TITLE
Unable to update pod

### ISSUE THREAD

**Issue by HathTech** [simolus3/sqlite3.dart#60]
Installing sqlite3 (3.32.3)
     > Http download
       $ /usr/bin/curl -f -L -o /var/folders/dn/9kj3z3_17pbd1h3f3mv_rc700000gn/T/d20211117-8200-1324sg9/file.zip
       https://www.sqlite.org/2020/sqlite-amalgamation-3320300.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.2 cocoapods-downloader/1.5.1'

    [!] Error installing sqlite3
    [!] /usr/bin/curl -f -L -o /var/folders/dn/9kj3z3_17pbd1h3f3mv_rc700000gn/T/d20211117-8200-1324sg9/file.zip
    https://www.sqlite.org/2020/sqlite-amalgamation-3320300.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.2 cocoapods-downloader/1.5.1'

      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0
  0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    curl: (60) SSL certificate problem: certificate has expired
    More details here: https://curl.haxx.se/docs/sslcerts.html

    curl failed to verify the legitimacy of the server and therefore could not
    establish a secure connection to it. To learn more about this situation and
    how to fix it, please visit the web page mentioned above.

**Comment by kuhnroyal** [comment]
This project only uses libraries from sqlite.org and has no influence over http certificates. You should probably raise a ticket over there or on the pod repo.

**Comment by simolus3** [comment]
True, although I am surprised that this could happen (it downloads fine for me, and AFAIK they only use one server). Maybe it was a temporary failure? Are you behind a corporate network that might interfere with things?

But as @kuhnroyal has said, this doesn't look like an issue originating from this project.
