### ISSUE TITLE
sqlite3_exec rows affected 

### ISSUE THREAD

**Issue by tofutim** [simolus3/sqlite3.dart#62]
Is there a reason db.execute does not return the number of rows affected from sqlite3_exec?

**Comment by simolus3** [comment]
The int returned by `sqlite3_exec` is actually a result code. If you want the amount of affected rows, use `sqlite3_changes` (or `getUpdatedRows()` in Dart).

I'm not opposed to changing `execute` for databases and prepared statements to return `sqlite3_changes` after running. But they're separate in sqlite3, so I think it's not unreasonable to split them in Dart either... Is is so inconvenient to call `getUpdatesRows` after `execute`?

**Comment by tofutim** [comment]
no i can accept that
