### ISSUE TITLE
long queries - async

### ISSUE THREAD

**Issue by tofutim** [simolus3/sqlite3.dart#64]
Are there thoughts on using async for long queries?

**Comment by simolus3** [comment]
This wouldn't help, as long-running queries are still a blocking C call in the end. If we made them async, they'd just block at some later point instead.

If you want to run queries in the backround, you'll have to use isolates.

**Comment by tofutim** [comment]
Can we work the isolates into the library so that we just await stmt.execute?

**Comment by simolus3** [comment]
I prefer this library to be a lightweight, but convenient, wrapper around sqlite3. Introducing builtin isolate support and all that comes with it shouldn't be a goal of this library. There are other packages which can do that for you:

- [sqflite_common_ffi](https://pub.dev/packages/sqflite_common_ffi) is built on top of this package and provides an async API backed by isolates internally.
- (shameless plug) I wrote [drift](https://pub.dev/packages/drift), which provides a ton of convenience features including proper isolate support.

**Comment by tofutim** [comment]
I saw drift, I will give it a spin...
