### ISSUE TITLE
Error web build

### ISSUE THREAD

**Issue by m2faridi** [simolus3/sqlite3.dart#66]
Hello
I can no longer get web output when I add your library to the project
I do not need a database in the web version
`../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.4.0/lib/src/api/database.dart:1:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^`

**Comment by simolus3** [comment]
Yes, the `sqlite3` package does not support the web platform. You could need to use [conditional imports](https://medium.com/@dvargahali/dart-2-conditional-imports-update-16147a776aa8) to make sure that you never import `sqlite3` when compiling to the web.
