### ISSUE TITLE
batch commands?

### ISSUE THREAD

**Issue by tofutim** [simolus3/sqlite3.dart#67]
Does sqlite3.dart support "INSERT...; SELECT LAST_INSERT_ROWID()" so that we can select and get the last id after inserting? I am trying to get the inserted new ID to put into another query in one step.

```
"INSERT INTO [35d738af6c304b009736abe5aaf184f4].Entries_content (
  word, definition, entryorder, freq
) VALUES (
  @word, @definition, @entryorder, @freq
);
SELECT LAST_INSERT_ROWID();"
```
When I select though, I get no rows. :(

I remember seeing it before in shell so that we can
```
sqlite> INSERT INTO test VALUES (2,3); SELECT LAST_INSERT_ROWID();
2
```

**Update.** I looked back and some old code I had used in C#, and we kept using the tail (pzTail, remains, etc.) until the queries were exhausted.
```
		public T ExecuteScalar<T> ()
		{
			if (_conn.Trace) {
				Debug.WriteLine ("Executing Query: " + this);
			}

			var rowsAffected = 0;

			T val = default(T);
			remainingText = CommandText.Trim().TrimEnd(';');
			while (!string.IsNullOrEmpty(remainingText))        // should cycle through
			{
				var stmt = Prepare();

				try
				{
					var colcount = SQLite3.ColumnCount(stmt);
					if (colcount > 0)
					{

						var r = SQLite3.Step(stmt);
						if (r == SQLite3.Result.Row)
						{
							var colType = SQLite3.ColumnType(stmt, 0);
							val = (T)ReadCol(stmt, 0, colType, typeof(T));
						}
						else if (r == SQLite3.Result.Done)
						{
						}
						else
						{
							throw SQLiteException.New(r, SQLite3.GetErrmsg(_conn.Handle));
						}
					}
					else
					{
						rowsAffected += stepNonQuery(stmt);
					}
				}
				finally
				{
					Finalize(stmt);
				}
			}

			return val;
		}
```

**Comment by simolus3** [comment]
I don't think that a `PreparedStatement` should implicitly cover more than one statement by stepping through the tail pointer. Combining multiple statements into one just yields to many questions like how parameters should bind etc.

However, we could have a `prepareMultiple` method that returns a list of prepared statements when passed a SQL string with multiple statements.

**Comment by simolus3** [comment]
I've added an API for this in d2c2dcf4659dffe197cea644ee80a4e7d82e31ed.
