### ISSUE TITLE
Web support?

### ISSUE THREAD

**Issue by mprogers** [simolus3/sqlite3.dart#69]
I'm trying to write a cross-platform Flutter app. Using this package, I've got an awesome version working on macOS and iOS -- thank you for writing it. The problem is on the web, it looks like ffi isn't supported (see error below), so I guess that's breaking this as well. Is there any way to get this to work on  Chrome desktop?

Launching lib/main.dart on Chrome in debug mode...
lib/main.dart:1
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-1.4.0/lib/src/api/database.dart:1:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^

**Comment by morningos** [comment]
How did you solve the problem?
I import it like `import 'package:sqlite3/sqlite3.dart if (dart.library.html) 'package:sqlite3/wasm.dart' as sqlite;` 
But it not works.

**Comment by simolus3** [comment]
It's not as simple as just changing an import unfortunately, as loading sqlite3 for the web requires some special setup whereas it is just there for the native platform. As such, there's also no `sqlite3` constant in `sqlite3/wasm.dart`.

It's probably best to extract the logic opening your database into a separate function and making that conditionally available, for instance like its done [here](https://github.com/simolus3/drift/tree/develop/examples/app/lib/database/connection).
