### ISSUE TITLE
App crashes on launch.

### ISSUE THREAD

**Issue by ali-cst** [simolus3/sqlite3.dart#77]
Hi, my app seem to crash in launch in a few different device models including (Emulator API 28 (9.0)), while in most works fine, after a while was able to locate it to this package. Any Idea ?

Device: Emulator API 28 (9.0).
sqlite3_flutter_libs: ^0.5.3
release build.

Log:
E/FlutterLoader(22322): Flutter initialization failed.
E/FlutterLoader(22322): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.app-UzPMcmDyxPEroQIURSnHWQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.app-UzPMcmDyxPEroQIURSnHWQ==/lib/x86, /data/app/com.app-UzPMcmDyxPEroQIURSnHWQ==/base.apk!/lib/x86, /system/lib]]] couldn't find "libflutter.so"
E/FlutterLoader(22322):         at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/FlutterLoader(22322):         at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/FlutterLoader(22322):         at io.flutter.embedding.engine.h.d.a(Unknown Source:28)
E/FlutterLoader(22322):         at io.flutter.embedding.engine.b.<init>(Unknown Source:214)
E/FlutterLoader(22322):         at io.flutter.embedding.engine.b.<init>(Unknown Source:12)
E/FlutterLoader(22322):         at io.flutter.embedding.android.f.o(Unknown Source:110)
E/FlutterLoader(22322):         at io.flutter.embedding.android.f.a(Unknown Source:7)
E/FlutterLoader(22322):         at io.flutter.embedding.android.e.onCreate(Unknown Source:15)
E/FlutterLoader(22322):         at android.app.Activity.performCreate(Activity.java:7136)
E/FlutterLoader(22322):         at android.app.Activity.performCreate(Activity.java:7127)
E/FlutterLoader(22322):         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
E/FlutterLoader(22322):         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
E/FlutterLoader(22322):         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
E/FlutterLoader(22322):         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/FlutterLoader(22322):         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/FlutterLoader(22322):         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/FlutterLoader(22322):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/FlutterLoader(22322):         at android.os.Handler.dispatchMessage(Handler.java:106)
E/FlutterLoader(22322):         at android.os.Looper.loop(Looper.java:193)
E/FlutterLoader(22322):         at android.app.ActivityThread.main(ActivityThread.java:6669)
E/FlutterLoader(22322):         at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader(22322):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/FlutterLoader(22322):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by simolus3** [comment]
Did you see [this note](https://github.com/simolus3/sqlite3.dart/tree/master/sqlite3_flutter_libs#included-platforms)? If you don't want to deploy to x86 Android devices, exclude that ABI in your build configuration.

**Comment by ali-cst** [comment]
> Did you see [this note](https://github.com/simolus3/sqlite3.dart/tree/master/sqlite3_flutter_libs#included-platforms)? If you don't want to deploy to x86 Android devices, exclude that ABI in your build configuration.

Very helpful, Thank you.
