### ISSUE TITLE
Flutter Linux App release: Failed to load dynamic library 'libsqlite3.so'

### ISSUE THREAD

**Issue by Endma** [simolus3/sqlite3.dart#79]
I have a multi-platform Flutter app for Android, Windows and Linux with a prepopulated SQLite DB. For Release builds
- on Android: works fine there to - the sqlite libraries  are included to the apk
- on Windows: I needed to add sqlite3.dll to the Release folder (no big deal).
- on Linux: I've tried to add libsqlite3.so (renamed a copy of libsqlite3.so.0.8.6 to libsqlite3.so) to the bundle folder and to bundle/lib folder (even tried it with libsqlite3.so.0 and libsqlite3.so.0.8.6 too), but no success - always the same error:

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libsqlite3.so': libsqlite3.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden

I guess it's just a path thing for the release build, like it should first search in it's folder (bundle/) or better in subfolder lib (bundle/lib/). Like for Windows, it finds the DLLs in the same folder as the app.exe is located.

pubspec.yaml 

dependencies:
  drift: ^1.4.0
  sqlite3_flutter_libs: ^0.5.3

dev_dependencies:
  drift_dev: ^1.4.0
  build_runner: ^2.1.7

I guess the issue is, that 'sqlite3_flutter_libs' doesn't support Linux yet?

**Comment by simolus3** [comment]
I think Linux only searches for `/lib` and `/usr/lib` by default. You can provide a full path to the shared object file though. There are some docs on that [here](https://drift.simonbinder.eu/docs/platforms/#bundling-sqlite-with-your-app) and in the readme of the `sqlite3` package.

**Comment by Endma** [comment]
Awesome, thanks! That was the missing info.
