### ISSUE TITLE
Failed to load dynamic library on Android

### ISSUE THREAD

**Issue by lwpie** [simolus3/sqlite3.dart#8]
```
ArgumentError (Invalid argument(s): Failed to load dynamic library (dlopen failed: library "/data/data/com.example.newsapp/lib/libsqlite3.so" not found))
```

**Comment by lwpie** [comment]
When I depends both on `sqlite3` and `sqlite3_flutter_libs`, errors occured as
```
SqliteException (SqliteException(14): bad parameter or other API misuse, bad parameter or other API misuse (code 21))
```

**Comment by lwpie** [comment]
I think it may be related to https://github.com/simolus3/moor/issues/731

**Comment by simolus3** [comment]
Does it work if you create the parent directory before opening a database in there?

**Comment by lwpie** [comment]
> Does it work if you create the parent directory before opening a database in there?

Which folder should I create before opening a database?

**Comment by simolus3** [comment]
If say you're opening a database in `$applicationDirectory/my_database.db`, you should make sure the parent folder (here, `$applicationDirectory`) exists before trying to open the database:

```dart
import 'package:path/path.dart' as p;

final dir = await getApplicationDocumentsDirectory();
if (! await dir.exists()) {
  await dir.create(recursive: true);
}
final db = sqlite3.open(p.join(dir.path, 'my_database.db'));
```

**Comment by lwpie** [comment]
That works, thank you!
