### ISSUE TITLE
Outdated SQLite on MacOS

### ISSUE THREAD

**Issue by westito** [simolus3/sqlite3.dart#81]
This package depends on macOS's built-in sqlite3 dylib that's version is 3.36.0 and can't be updated. The code first try to load global dylib and falls back to `/usr/lib/libsqlite3.dylib`. This must be swapped. MacOS always have a global sqlite dylib, so a custom installed sqlite to `/usr/lib/libsqlite3.dylib` can never load. 

Usually sqlite3 is installed by Homebrew or Ports, and rarely by custom build to `/usr/lib`
I recommend this fallback order:
- `/opt/homebrew/opt/sqlite/lib/libsqlite3.dylib`
- `/opt/local/lib/libsqlite3.dylib`
- `/usr/lib/libsqlite3.dylib`
- `Global`

This only affects `dart test` and macOS apps without `sqlite3_flutter_libs` provided in `pubspec.yaml`
I found this problem when testing Drift locally. Tests fail with `SqliteException(1): near "STRICT": syntax error`. This keyword exists from SQLite 3.37, macOS have SQLite 3.36 by default. 

I make a PR for this.

**Comment by westito** [comment]
I found an issue with my fallback order. `Global` is different in CLI / Flutter. When code running in Flutter, the `Global` (means the bundled lib) must be loaded first (so your code is valid in deed, sorry), but running in CLI it must be loaded in the end. Can we detect that the code run on Flutter or not?

**Comment by westito** [comment]
The `Platform.resolvedExecutable` is the solution I think. With testing this is the dart executable. Running CLI app it can be anything. But running as Flutter it is contains `Contents/MacOS` surely. Checking this would be enough I think.

**Comment by simolus3** [comment]
> The `Platform.resolvedExecutable` is the solution I think. With testing this is the dart executable. Running CLI app it can be anything. But running as Flutter it is contains `Contents/MacOS` surely. Checking this would be enough I think.

Yes, this check sounds reasonable 👍

**Comment by westito** [comment]
I'm stuck. 
`DynamicLibrary.open('/opt/homebrew/Cellar/sqlite/3.38.0/lib/libsqlite3.0.dylib')` returns the same handle as `DynamicLibrary.open('/usr/lib/libsqlite3.dylib')`. Tried with different dylibs, but the result is the same.
I tried to load the custom sqlite3 library with `dlopen`, but returns the same handle as above too. The problem is OS level.

**Comment by simolus3** [comment]
Yeah, I think I hit something similar back when I originally implemented the opening logic but I blamed it on my lack of understanding of macOS.

> Tried with different dylibs

Does it work if it doesn't end in `libsqlite3.dylib` or is that what you meant with different dylibs? I assume sqlite3 is special-cased at some point in the loader, but I don't know why and how one might trick it.

**Comment by kuhnroyal** [comment]
I am using `DynamicLibrary.open('/usr/local/opt/sqlite/bin/sqlite3')` which is installed via homebrew.
Also I noticed that once you do anything with sqlite (like calling `sqlite3.version`) before calling `DynamicLibrary.open`, then it will always bind to the system default.

Maybe https://github.com/simolus3/drift/discussions/1745#discussioncomment-2326294 can help.

**Comment by simolus3** [comment]
A problem might be that we use `Process.executable()` here? https://github.com/simolus3/sqlite3.dart/blob/bfd53fd9bc284bfcb2fe9de7afa2a83544a9fe11/sqlite3/lib/src/ffi/load_library.dart#L70

The intention is to check whether sqlite3 has been statically linked into the running program, but it actually checks whether sqlite3 has been opened through some way at runtime. This should probably be `Process.executable()`.

> `DynamicLibrary.open('/opt/homebrew/Cellar/sqlite/3.38.0/lib/libsqlite3.0.dylib')` returns the same handle as `DynamicLibrary.open('/usr/lib/libsqlite3.dylib')

IIRC, as soon as you have _any_ library open (doesn't matter from where), loading the same library name again but from a different path is just going to give you the first library. At least it's like that on Android, wouldn't surprise me if it's like that across UNIXes.

**Comment by westito** [comment]
The problem goes away! Still can't load other library, but the default macOS version is updated to 3.37.0 what can handle STRICT that I missed before. Maybe the last macOS 12.3 update did this (3 days after I created this issue 😄). I can't find any note on this. So this issue not relevant anymore.
