### ISSUE TITLE
Also bundle sqlite3 on Linux and Windows

### ISSUE THREAD

**Issue by simolus3** [simolus3/sqlite3.dart#82]
The `sqlite3_flutter_libs` package supports Android, iOS and macOS out-of-the box. Support for Windows and Linux requires additional setup by providing the dynamic library as a file or linking it into the application.

This is causing lots of confusion for users, so let's consider linking sqlite3 into the application. This will also ensure that users get a consistent sqlite3 build with the same compile-time args across platforms.

**Comment by simolus3** [comment]
I've added builtin support for Linux in d71ab641cdd9ebbc330ab5152d317c03ac28f3b0. I don't have a Windows machine at hand right now, but a similar approach should probably work. Contributions are welcome!

**Comment by kuhnroyal** [comment]
Great news, thinking of recent discussions, it would probably be great if we can find a simple way of also making use of these bindings in unit tests. Just not sure how.

**Comment by simolus3** [comment]
I've thought about assuming that `flutter run` has been run recently. We could then load something like `build/linux/<arch>/bundle/lib/libsqlite3_flutter_libs_plugin.so` which contains sqlite3 (or another path on different platforms). On Linux, a problem is that `libsqlite3_flutter_libs_plugin.so` also contains the registrar setup. For me, the library segfaults outside of Flutter.

At least on Windows this could work though, because there we're forced to ship `sqlite3.dll` as a separate file.
