### ISSUE TITLE
SharedWorker support

### ISSUE THREAD

**Issue by westito** [simolus3/sqlite3.dart#84]
There is a plan for SharedWorker connection like in Drift?

**Comment by simolus3** [comment]
Getting the remote protocol to work in Drift was complicated enough, I'm not too interested in adding a similar mechanism to this package as well :D

I think this package should be a very low-level wrapper around sqlite3. We make some APIs more convenient for Dart users, but in general there's not a lot of "magic" happening in this package that would be hidden from the user. I don't think builtin support for workers would be a good fit for this package. It would likely require an async API as well.

In 251d0805c03dd89c19b6db06fc88b926c6916a8d, I've added support for running on web workers. But I think a transparent connection to run a database in a shared worker and to access it from the UI thread belongs to higher-level packages like Drift. If you only need the shared worker connection, you can just depend on Drift, subclass `GeneratedDatabase` without code generation and then only use custom statements. That way, you essentially have the API to run queries in a shared worker and to synchronize results.
