### ISSUE TITLE
sqlite3 1.6.2 depends on js ^0.6.4

### ISSUE THREAD

**Issue by adpg** [simolus3/sqlite3.dart#86]
First up, big thanks for creating this package, in particular for the work on Web support, as I am trying to extend a mobile app to a web version using sqlite.

However, in this process I ran into a version solving conflict when trying to add dependency for sqlite3 in pubspec.yaml, apparently due to sqlite3 depending on js 0.6.4. Several packages I'm using in the mobile app version depend on js 0.6.3, judging from the 'pub get failed' messages:

`“Because no versions of sqlite3 match >1.6.2 <2.0.0 and sqlite3 1.6.2 depends on js ^0.6.4, sqlite3 ^1.6.2 requires js ^0.6.4.
And because [package name] depends on flutter_web_plugins from sdk which depends on js 0.6.3, version solving failed."
`

Any idea how to solve this or work around this problem?

**Comment by simolus3** [comment]
Unfortunately we really do need version `0.6.4` as a lower bound for `sqlite3`, we're using `@staticInterop` in the WebAssembly module loading code.

The good news is that Flutter already depends on `0.6.4` on its master channel, so this problem will likely solve itself in the next Flutter version. Until then, you can try adding this to your pubspec:

```yaml
dependency_overrides:
  js: ^0.6.4
```
