### ISSUE TITLE
Web app using an existing database

### ISSUE THREAD

**Issue by adpg** [simolus3/sqlite3.dart#87]
I'm trying to use a pre-populated sqlite database, with tables and data already created and inserted, within a flutter web app. Based on [this example](https://github.com/simolus3/sqlite3.dart/blob/main/sqlite3/example/web/main.dart), I've been using the following code:

    final fs = await IndexedDbFileSystem.load('/db/');
    print ('loaded fs');

    final response = await http.get(Uri.parse('sqlite3.wasm'));
    final sqlite = await WasmSqlite3.load(
        response.bodyBytes, SqliteEnvironment(fileSystem: fs));

    print('Version of sqlite used is ${sqlite.version}');

    final db = sqlite.open('/db/FSQ3DB_start.db');

    print('userVersion: ${db.userVersion}');

    print(db.select('''
      SELECT name
      FROM sqlite_master
      '''
    )); 

which gives the following console output:
loaded fs
Version of sqlite used is Version(libVersion: 3.38.2, sourceId: 2022-03-26 13:51:10 d33c709cc0af66bc5b6dc6216eba9f1f0b40960b9ae83694c986fbf4c1d6f08f, number: 3038002)
userVersion: 0
()

So, everything looks OK up until a list of tables I know to be in the db should be printed, but this results in empty output: ()
Also, trying to query an existing table causes an error:
 Unhandled error SqliteException(1): no such table: [table name], SQL logic error (code 1).

Am I doing something wrong, or is it not possible to use an existing, pre-populated database?

**Comment by simolus3** [comment]
How exactly are you pre-populating the database? I don't see anything in your snippet that would be doing that. I would probably just write the existing database file into the file system:

```dart
Uint8List existingDatabase; // bytes for an existing file
const path = '/db/FSQ3DB_start.db';

final fs = await IndexedDbFileSystem.load('/db/');
if (!fs.exists(path)) {
  fs
    ..createFile(path)
    ..write(path, existingDatabase, 0);
}

final db = sqlite.open('/db/FSQ3DB_start.db');
```

**Comment by adpg** [comment]
> How exactly are you pre-populating the database? I don't see anything in your snippet that would be doing that. 

Correct, I meant using a database file from disk with tables created and data already inserted.
So you were right about writing the existing database file into the file system. Adapting your code suggestion I got this to work (using code parts from the mobile app version, which uses the same starter db on disk to create an sqlite db):

    
    Uint8List existingDatabase;
    const path = '/db/FSQ3DB_start.db';

    final fs = await IndexedDbFileSystem.load('/db/');
    if (!fs.exists(path)) {
      final data = await rootBundle.load(
          join("assets", "data", "db_start", "FSQ3DB_start.db")); // loading procedure from mobile app
      existingDatabase = data.buffer.asUint8List(0, data.lengthInBytes);
      fs
        ..createFile(path)
        ..write(path, existingDatabase, 0);
    }

    final response = await http.get(Uri.parse('sqlite3.wasm'));
    final sqlite = await WasmSqlite3.load(
        response.bodyBytes, SqliteEnvironment(fileSystem: fs));

    print('Version of sqlite used is ${sqlite.version}');

    print('opening a persistent database');

    final db = sqlite.open('/db/FSQ3DB_start.db');

    print('userVersion: ${db!.userVersion}');

    print(db.select('''
      SELECT name
      FROM sqlite_master
      '''
    ));



Interestingly, the db.userVersion now prints out as:

`  userversion: 3200000`

But apparently something in loading/writing goes wrong, as the following error is produced :

`Error: Unhandled error SqliteException(11): malformed database schema (I), database disk image is malformed (code 11)
  Causing statement:       SELECT name
      FROM sqlite_master`

So I wonder if the rootBundle.load is the right procedure to retrieve the binary file data? Or whether data.buffer.asUint8List(0, data.lengthInBytes) is the right way to access and write the bytes to disk?

**Comment by simolus3** [comment]
Hm, I couldn't reproduce this. I'm not using Flutter, so this is what I did:

- Ran `sqlite3 /tmp/test.db` on my computer and created a simple table (`CREATE TABLE foo (a, b);`)
- Ran `cat /tmp/test.db | base64 -w 0` to store the database in a base64 string

Then, I essentially just used this:

```dart
import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:sqlite3/wasm.dart';

const _database = '<base64 output>';

Future<void> main() async {
  final fs = await IndexedDbFileSystem.load('/db/')
    ..createFile('/db/test.db')
    ..write('/db/test.db', base64.decode(_database), 0);

  final response = await http.get(Uri.parse('sqlite3.wasm'));
  final sqlite = await WasmSqlite3.load(
      response.bodyBytes, SqliteEnvironment(fileSystem: fs));

  final db = sqlite.open('/db/test.db');
  print(db.select('select * from sqlite_schema'));
}
```

This is working fine for me. Perhaps it's something with how the asset is loaded?

**Comment by adpg** [comment]
Following your comment, I also created a new simple database with a single table, and this one loaded OK.

Combining this with the SqliteException error I got when trying to import my starter database ...

> Error: Unhandled error SqliteException(11): malformed database schema (I), database disk image is malformed (code 11) Causing statement: SELECT name FROM sqlite_master

... I figured this starter database file had some flaw in it, although this doesn't show up when it is loaded in the mobile version (also, when I checked this db using PRAGMA integrity_check, it reported back 'ok').

I then exported/imported the starter db to/from sql to create a fresh database file including all of the original tables and data. Lo and behold, loading this new db ended up OK. Clearly, I should have paid more attention to the SqliteException error ...

So importing an existing db works! Many thanks for all your work in helping me out!

**Comment by rodydavis** [comment]
Slightly similar issue but on flutter web i ran into this issue, but using the wasm database. Interesting that 'filesystem' is considered optional because it would not load the database again after a hot restart:

```dart
import 'dart:async';

// ignore: avoid_web_libraries_in_flutter
import 'dart:html';

import 'package:drift/drift.dart';
import 'package:drift/remote.dart';
import 'package:drift/web.dart';
import 'package:drift/wasm.dart';
import 'package:http/http.dart' as http;
import 'package:sqlite3/wasm.dart';

DatabaseConnection connect(
  String dbName, {
  bool useWebWorker = false,
  bool logStatements = false,
}) {
  if (useWebWorker) {
    final worker = SharedWorker('shared_worker.dart.js');
    return remote(worker.port!.channel());
  } else {
    return DatabaseConnection.delayed(Future.sync(() async {
      final response = await http.get(Uri.parse('sqlite3.wasm'));
      final fs = await IndexedDbFileSystem.open(dbName: '/db/');
      final path = '/drift/db/$dbName';
      final sqlite3 = await WasmSqlite3.load(
        response.bodyBytes,
        SqliteEnvironment(fileSystem: fs),
      );
      final databaseImpl = WasmDatabase(
        sqlite3: sqlite3,
        path: path,
        fileSystem: fs, // <- this is required but not documented
        logStatements: logStatements,
      );
      return DatabaseConnection(databaseImpl);
    }));
  }
}

```

Including it makes everything work though.
