### ISSUE TITLE
Serialization Mechanism

### ISSUE THREAD

**Issue by Ayad-Ben-Saliem** [simolus3/sqlite3.dart#88]
Hello,

Is there any mechanism to implement object serialization in sqlite3

Ex.
I have a user model like this
```
class User {
    final ObjectId id; // from https://pub.dev/packages/objectid
    final String name;
    ...
}
```
When I save a user 
```
void saveUser(User user) {
    // This throws an error while sqlite3 doesn't know how to serialize `id` (ObjectId)
    _db.execute('INSERT INTO Users (id, name) VALUES (?, ?)', [id, name]);

    // Instead I use `id.hexString` like this
    _db.execute('INSERT INTO Users (id, name) VALUES (?, ?)', [id.hexString, name]);
}
```

It's better if I can implement a serialization mechanism.

**Comment by simolus3** [comment]
Thanks for starting this discussion! However, I think this package should be a low-level wrapper around sqlite3. Obviously we map patterns from a C library like sqlite3 to make sense in a Dart library, but automatically managing serialization for you is not in scope for a pure database library IMO.

You could use a more high-level library like [drift](https://drift.simonbinder.eu/) (also written by yours truly) which supports setting type converters on columns and can use the `sqlite3` package internally. Other packages like [floor](https://pub.dev/packages/floor) also support type converters, but I don't know whether they use this package.
