### ISSUE TITLE
sqlite_flutter_libs segfaults on linux

### ISSUE THREAD

**Issue by antony-jr** [simolus3/sqlite3.dart#91]
I'm on OpenSUSE Tumbleweed and it's a rolling distro. Using sqlite_flutter_libs segfaults the Flutter app when trying to open a database. When I use the system provided sqlite library the issue does not occur (i.e by removing sqlite_flutter_libs).

**Comment by simolus3** [comment]
Im on Manjaro and I've never seen this segfault. Can you get more information on this (some kind of trace with symbols maybe)? Does this happen every time? I can try to reproduce it in a VM but it'll take some time to set up so I appreciate more details on this.

**Comment by antony-jr** [comment]
> Im on Manjaro and I've never seen this segfault. Can you get more information on this (some kind of trace with symbols maybe)? Does this happen every time? I can try to reproduce it in a VM but it'll take some time to set up so I appreciate more details on this.

I will try to provide more info on this. I think the problem might be in my distro if it works on Manjaro. Thank for the fast reply. (btw I'm using v0.5.5 of sqlite_flutter_libs package from pub)

**Comment by ShubhamVG** [comment]
@antony-jr Do you have any updates? This issue has been opened for far too long.

**Comment by antony-jr** [comment]
I think we can close this, im not using the lib actively now

**Comment by simolus3** [comment]
It looks like @ShubhamVG might be running into the same issue - could you also share more details about your system or the crash you're running into?

**Comment by ShubhamVG** [comment]
> It looks like @ShubhamVG might be running into the same issue - could you also share more details about your system or the crash you're running into?

Actually no. I came across this package so I was just inspecting the repo. I have not used this package yet. I am making a project with it but I haven't ran it yet. In case I get any issues, you will know. :+1:

**Comment by antony-jr** [comment]
For me, it works on dev build but fails on release builds, but I have to test it with the latest version to test if this actually exists now.
