### ISSUE TITLE
Add support for the RETURNING modifier on the flutter / dart side.

### ISSUE THREAD

**Issue by appsmatics** [simolus3/sqlite3.dart#93]
sqlite v 3.35 onwards returns the id or the row of the INSERT UPDATE or DELETE
    https://www.sqlite.org/lang_returning.html
Pls expose this from the dart / flutter side. Currently using db.lastInsertRowId, but could have race errors.

flutter: Using sqlite3 Version(libVersion: 3.38.2, sourceId: 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1, number: 3031001)

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SqliteException(1): near "RETURNING": syntax error, SQL logic error (code 1)
  Causing statement: INSERT INTO  albums (
      title, description, created_at
    ) VALUES (?,?,?) RETURNING *
#0      throwException (package:sqlite3/src/impl/exception.dart:34:3)
#1      DatabaseImpl._prepareInternal (package:sqlite3/src/impl/database.dart:250:9)
#2      DatabaseImpl.prepare (package:sqlite3/src/impl/database.dart:152:19)
#3      addAlbumToDb (package:taft_photos/PhotosModule/Model/album_info.dart:119:20)
<asynchronous suspension>
```

[ps: apologies for this showing up in bold, just could not get rid of it :( ]
Works from the sqlite3 shell:
```
SQLite version 3.38.2 2022-03-26 13:51:10
Enter ".help" for usage hints.
sqlite> insert into images (path) VALUES ("Pictures/20220121_184633.jpg") RETURNING id;
id
--
1 
```

**Comment by simolus3** [comment]
Thanks for the report! By the way, you can wrap code or formatted text in tripple backticks to show up like that, then you also avoid `--` on a single line being interpreted as a headline :)

That said, I'm a bit surprised about this since this library supports `RETURNING` on sqlite versions that do, and we have a bunch of tests for that https://github.com/simolus3/sqlite3.dart/blob/1621594c049101ddf4ac749dea00c354ce8a1fef/sqlite3/test/common/prepared_statement.dart#L315-L320

Could you post the code you've used for this? Then I can try to reproduce it.

> Using sqlite3 Version(libVersion: 3.38.2, sourceId: 2020-01-27

This is really weird, sqlite 3.38.2 was released a couple months ago, not in early 2020. Is this on iOS or Android? Perhaps there's something bad going on and your linking different sqlite3 versions into your app for some reason?

**Comment by appsmatics** [comment]
Thanks Simon!. (for that triple backticks tip as well)

Now you got me as what is happening with my sqlite version. 
Using   sqlite3: ^1.5.1
I apt-get removed the system one from /usr. 
The only other sqlite3 binary is in my ~/opt/sqlite/3.38 that I compiled from source for FTS5 and enable readline. 
I also removed the sqlite3_flutter_libs: ^0.5.5 from pubspec and this is what I get ..

flutter: Using sqlite3 Version(libVersion: 3.31.1, sourceId: 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1, number: 3031001)

Platform is Ubuntu 20.04.
Does sqlite3 install some default libs ? 
Where does the sqlite3_flutter_libs install the sqlite3 ?
Thanks !

**Comment by simolus3** [comment]
> Where does the sqlite3_flutter_libs install the sqlite3 ?

It downloads and compiles them automatically, the final `.so` is going to be somewhere in `build/Linux`. Could you run a clean Linux build with `--verbose`? It would be interesting to see the exact compile options passed to the step compiling sqlite3. Maybe there's a mismatch between `sqlite3.h` and `sqlite3.c` causing this.

**Comment by appsmatics** [comment]
Yeah right, something weird in my project setup. Will do some cleaning up!

I did try a separate project and it reported

Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
flutter: Using sqlite3 Version(libVersion: 3.38.3, sourceId: 2022-04-27 12:03:15 9547e2c38a1c6f751a77d4d796894dec4dc5d8f5d79b1cd39e1ffc50df7b3be4, number: 3038003)

was able to use the INSERT INTO ... RETURNING (but using the db.select as db.execute returns a void).

You can close out the issue please. Thanks for your time !
