### ISSUE TITLE
Unable to compile with drift 1.6.0

### ISSUE THREAD

**Issue by jeannelim** [simolus3/sqlite3.dart#94]
Hi,

I'm trying to use the latest drift v1.6.0 in our flutter app but it's not compiling. We use packages that depend on flutter_web_plugins and flutter_web_plugins depend on js v0.6.3. This conflicts with js v0.6.4 in sqlite3 package. How were you able to run the latest drift? I was looking at drift's pubspec and it also has js v0.6.3.

**Comment by simolus3** [comment]
This package uses `@staticInterop` interop, so we really do need version 0.6.4 of `package:js`.

The solution is to wait for Flutter to support the latest dependencies, or to add `js: ^0.6.4` to your `dependency_overrides`.
