### ISSUE TITLE
Does sqlcipher_flutter_libs support Windows, Linux platforms?

### ISSUE THREAD

**Issue by Shuhrat-java** [simolus3/sqlite3.dart#99]
Hello,
Was not sure where to ask this question. On pub.dev website it is said that sqlcipher_flutter_libs supports only android, ios, Macos platforms. However here it is said that all 5 platforms are supported. Can you make it clear for us? Thanks in advance.

**Comment by simolus3** [comment]
It does support both Linux and Windows recent versions. For me, those platforms are also listed on [its pub.dev page](https://pub.dev/packages/sqlite3_flutter_libs). I might have missed some description, where exactly does it say that it only supports Android, iOS and macOS?
